In [1]:
from __future__ import print_function, division

import tensorflow as tf

print(tf.__version__)

import keras

import matplotlib.pyplot as plt

import sys

from sklearn import preprocessing

import time
from tqdm import tqdm

from imutils import paths
from numpy import *
import numpy as np

from matplotlib.colors import Normalize

import argparse
import imutils,sklearn
import os, cv2, re, random, shutil, imageio, pickle

%matplotlib inline  

1.3.0


/home/huiqy/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
def atoi(text):
    return int(text) if text.isdigit() else text

def natural_keys(text):
    return [ atoi(c) for c in re.split('(\d+)', text) ]

def load_flower_data():
    # grab the list of images that we'll be describing
    print("[INFO] handling images...")
    TRAIN_ORIGINAL_DIR = './subsample/'
    TEST_DIR = './test/'

    # use this for full dataset
    train_images = [TRAIN_ORIGINAL_DIR + i for i in os.listdir(TRAIN_ORIGINAL_DIR)]
    test_images = [TEST_DIR + i for i in os.listdir(TEST_DIR)]
    
    train_images.sort(key=natural_keys)
    test_images.sort(key=natural_keys)

    # initialize the features matrix and labels list
    trainImage = []
    trainLabels = []
    testImage = []
    testLabels = []

    # loop over the input images
    for (i, imagePath) in enumerate(train_images):
        # extract the class label
        # get the labels from the name of the images by extract the string before "_"
        label = imagePath.split(os.path.sep)[-1].split("_")[0]

        # read and resize image
        img = cv2.imread(imagePath)
        img = cv2.resize(img, (128,128))

        # add the messages we got to features and labels matricies
        trainImage.append(img)
        trainLabels.append(label)

        # show an update every 100 images until the last image
        if i > 0 and ((i + 1) % 1000 == 0 or i == len(train_images) - 1):
            print("[INFO] processed {}/{}".format(i + 1, len(train_images)))
            
      # loop over the input images
    for (i, imagePath) in enumerate(test_images):
        # extract the class label
        # our images were named as labels.image_number.format
        # get the labels from the name of the images by extract the string before "."
        label = imagePath.split(os.path.sep)[-1].split("_")[0]

        # extract CNN features in the image
        img = cv2.imread(imagePath)
        img = cv2.resize(img, (128,128))

        # add the messages we got to features and labels matricies
        testImage.append(img)
        testLabels.append(label)

        # show an update every 100 images until the last image
        if i > 0 and ((i + 1) % 1000 == 0 or i == len(test_images) - 1):
            print("[INFO] processed {}/{}".format(i + 1, len(test_images)))


    trainImage = np.array(trainImage,dtype = float32)
    trainLabels = np.array(trainLabels)
    testImage = np.array(testImage,dtype = float32)
    testLabels = np.array(testLabels)
    print (trainImage.shape)
    
    trainImage = trainImage.astype(np.float32) / 255
    testImage = testImage.astype(np.float32) / 255
    
    le = preprocessing.LabelEncoder()
    le.fit(trainLabels)
    list(le.classes_)
    trainLabels = le.transform(trainLabels) 
    testLabels = le.transform(testLabels) 
    
    return trainImage, trainLabels, testImage, testLabels

In [3]:
trainImage, trainLabels, testImage, testLabels = load_flower_data()

nb_classes = 4

# Convert class vectors to binary class matrices.
trainLabels = keras.utils.to_categorical(trainLabels, nb_classes)
print (trainLabels)
testLabels = keras.utils.to_categorical(testLabels, nb_classes)
print (testLabels)
print (testLabels.shape)

np.save('../trainImage.npy', trainImage)
np.save('../trainLabels.npy', trainLabels)
np.save('../testImage.npy', testImage)
np.save('../testLabels.npy', testLabels)

print("[INFO] trainImage matrix: {:.2f}MB".format(
    (trainImage.nbytes) / (1024 * 1000.0)))
print("[INFO] trainLabels matrix: {:.4f}MB".format(
    (trainLabels.nbytes) / (1024 * 1000.0)))
print("[INFO] testImage matrix: {:.2f}MB".format(
    (testImage.nbytes) / (1024 * 1000.0)))
print("[INFO] testLabels matrix: {:.4f}MB".format(
    (testLabels.nbytes) / (1024 * 1000.0)))


[INFO] handling images...
[INFO] processed 1000/16000
[INFO] processed 2000/16000
[INFO] processed 3000/16000
[INFO] processed 4000/16000
[INFO] processed 5000/16000
[INFO] processed 6000/16000
[INFO] processed 7000/16000
[INFO] processed 8000/16000
[INFO] processed 9000/16000
[INFO] processed 10000/16000
[INFO] processed 11000/16000
[INFO] processed 12000/16000
[INFO] processed 13000/16000
[INFO] processed 14000/16000
[INFO] processed 15000/16000
[INFO] processed 16000/16000
[INFO] processed 160/160
(16000, 128, 128, 3)
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [

In [4]:
class CNN(object):
    def __init__(self, sess, epoch, batch_size, dataset_name, checkpoint_dir, log_dir, trainhist_dir):
        self.sess = sess
        self.dataset_name = dataset_name
        self.checkpoint_dir = checkpoint_dir
        self.log_dir = log_dir
        self.trainhist_dir = trainhist_dir
        self.epoch = epoch
        self.batch_size = batch_size


        # parameters
        self.input_height = 128
        self.input_width = 128
        self.c_dim = 3  # color dimension
        self.nb_class = 4
        
        # number of convolutional filters to use  
        self.nb_CNN = [32, 64, 64, 64, 128]    
        # number of dense filters to use  
        self.nb_Dense = [128] 
        # size of pooling area for max pooling  
        self.pool_size = (2, 2)  
        # convolution kernel size  
        self.kernel_size = (3, 3)
        self.batch_normalization_control = True
        
        # train   
        self.global_step = tf.Variable(0, trainable=False)
        self.initial_lr = 0.001 #初始学习率
        self.decay_steps = 10
        self.decay_rate = 0.9
        self.lr = tf.train.exponential_decay( self.initial_lr,
                                     global_step=self.global_step,
                                     decay_steps=self.decay_steps,
                                     decay_rate=self.decay_rate)
        self.beta1 = 0.5
        #max model to keep saving
        self.max_to_keep = 300

        # name for checkpoint
        self.model_name = 'CNN_C%d_D%d_Kernel(%d,%d)_%d_lrdecay0.0001' % (len(self.nb_CNN), len(self.nb_Dense),
                                                          self.kernel_size[0], self.kernel_size[1], max(self.nb_CNN))    
        
        # test

        #load_flower_data
        self.train_x = np.load('../trainImage.npy')
        self.train_y= np.load('../trainLabels.npy')
        self.test_x = np.load('../testImage.npy')
        self.test_y= np.load('../testLabels.npy')
        
        print ("Training:",self.train_x.shape[0])
        
        #记录
        self.train_hist = {}
        self.train_hist['losses'] = []
        self.train_hist['accuracy'] = []
        self.train_hist['learning_rate'] = []
        self.train_hist['per_epoch_ptimes'] = []
        self.train_hist['total_ptime'] = []
        
        # get number of batches for a single epoch
        self.num_batches_train = len(self.train_x) // self.batch_size
        self.num_batches_test= len(self.test_x) // self.batch_size

    def cnn_model(self, x, keep_prob, is_training=True, reuse=False):
        with tf.variable_scope("cnn", reuse=reuse):
             
            #初始化参数
            W = tf.truncated_normal_initializer(mean=0.0, stddev=0.02)
            B = tf.constant_initializer(0.0)
        
            print("CNN:x",x.get_shape()) # 128, 128, 3 

            #输入,卷积核为3*3 输出维度为32
            net = tf.layers.conv2d(inputs = x,                 # 输入,
                                    filters = self.nb_CNN[0],      # 卷积核个数,
                                    kernel_size = self.kernel_size,          # 卷积核尺寸
                                    strides = (1, 1),
                                    padding = 'same',              # padding方法
                                    kernel_initializer = W,
                                    bias_initializer = B,
                                    kernel_regularizer = None,
                                    bias_regularizer = None,
                                    activity_regularizer = None,
                                    name = 'conv_1'               # 命名用于获取变量
                                    )
            print("CNN:",net.get_shape())

            if self.batch_normalization_control:
                net = tf.layers.batch_normalization(net, training=is_training)
            net = tf.nn.relu(net, name = 'relu_conv_1')
            net = tf.layers.max_pooling2d(inputs = net,
                                          pool_size = self.pool_size,
                                          strides = (2, 2),
                                          padding='same',
                                          name='pool_conv_' + str(1)
                                         )
            print("CNN:",net.get_shape())
            
            for i in range(2,len(self.nb_CNN)+1):
                net = tf.layers.conv2d(inputs = net,                 # 输入,
                                       filters = self.nb_CNN[i-1],      # 卷积核个数,
                                       kernel_size = self.kernel_size,          # 卷积核尺寸
                                       strides = (1, 1),
                                       padding = 'same',              # padding方法
                                       kernel_initializer = W,
                                       bias_initializer = B,
                                       kernel_regularizer = None,
                                       bias_regularizer = None,
                                       activity_regularizer = None,
                                       name = 'conv_'+ str(i)        # 命名用于获取变量
                                       )
                print("CNN:",net.get_shape())
                if self.batch_normalization_control:
                    net = tf.layers.batch_normalization(net, training=is_training)
                net = tf.nn.relu( net, name = 'relu_conv_' + str(i))
                net = tf.layers.max_pooling2d(inputs = net,
                                              pool_size = self.pool_size,
                                              strides = (2, 2),
                                              padding = 'same',
                                              name = 'pool_conv_' + str(i)
                                             )

                print("CNN:",net.get_shape())

            #flatten
            net = tf.reshape(net, [-1, int(net.get_shape()[1]*net.get_shape()[2]*net.get_shape()[3])],name='flatten')
            print("CNN:",net.get_shape())
            
            #dense layer
            for i in range(1,len(self.nb_Dense)+1):
                net = tf.layers.dense(inputs = net,
                                    units = self.nb_Dense[i-1],
                                    kernel_initializer = W,
                                    bias_initializer = B,
                                    kernel_regularizer=None,
                                    bias_regularizer=None,
                                    activity_regularizer=None,
                                    name = 'dense_' + str(i)
                                    )
#                 net = tf.layers.batch_normalization(net, training=is_training)
                net = tf.nn.relu( net, name = 'relu_dense_' + str(i))
                net = tf.layers.dropout(inputs = net,
                                        rate=keep_prob,
                                        noise_shape=None,
                                        seed=None,
                                        training = is_training,
                                        name= 'dropout_dense_' + str(i)
                                        )
            #output
            logit = tf.layers.dense(inputs = net,
                                    units = self.nb_class,
                                    kernel_initializer = W,
                                    bias_initializer = B,
                                    kernel_regularizer=None,
                                    bias_regularizer=None,
                                    activity_regularizer=None,
                                    name = 'dense_output'
                                    )
            out_logit = tf.nn.softmax(logit, name="softmax")
            print("CNN:out_logit",out_logit.get_shape())
            print("------------------------")    

            return out_logit, logit


    def build_model(self):

        """ Graph Input """
        # images
        self.x = tf.placeholder(tf.float32, shape=[self.batch_size,self.input_height, self.input_width, self.c_dim], 
                                name='x_image')

        self.y = tf.placeholder(tf.float32, shape=[self.batch_size, self.nb_class], name='y_label')
        
        self.keep_prob = tf.placeholder(tf.float32)
        
        self.add_global = self.global_step.assign_add(1)

        """ Loss Function """

        # output of cnn_model
        self.out_logit, self.logit = self.cnn_model(self.x, self.keep_prob, is_training=True, reuse=False)
        
        self.loss_cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=self.y,
                                                                                         logits =self.logit))
        
        """ Training """
        tf_vars = tf.trainable_variables()
        cnn_vars = [var for var in tf_vars if var.name.startswith('cnn')]

        # optimizers
        with tf.control_dependencies(tf.get_collection(tf.GraphKeys.UPDATE_OPS)):
            self.cnn_optim = tf.train.AdamOptimizer(self.lr, beta1=self.beta1).minimize(self.loss_cross_entropy,
                                                                                        var_list=cnn_vars)
            
        """" Testing """
        # for test
        # output of cnn_model
        self.out_logit_test, self.logit_test = self.cnn_model(self.x, self.keep_prob, is_training=False, reuse=True)
        self.correct_prediction = tf.equal(tf.argmax(self.logit_test, 1), tf.argmax(self.y, 1))
        self.predict = tf.argmax(self.logit_test, 1)
        self.accuracy = tf.reduce_mean(tf.cast(self.correct_prediction, tf.float32))

        """ Summary """
        self.loss_sum = tf.summary.scalar("loss", self.loss_cross_entropy)


    def train(self):

        # initialize all variables
        tf.global_variables_initializer().run()

        # saver to save model
        self.saver = tf.train.Saver(max_to_keep = self.max_to_keep)

        # summary writer
        self.writer = tf.summary.FileWriter(self.log_dir + '/' + self.model_name, self.sess.graph)

        # restore check-point if it exits
        could_load, checkpoint_epoch = self.load(self.checkpoint_dir)
        if could_load:
            start_epoch = (int)(checkpoint_epoch) + 1
            counter = 1
            f = open(self.trainhist_dir + '/' + self.model_name+'_train_hist.pkl', 'rb') 
            self.train_hist = pickle.load(f)
            f.close()
            print(" [*] Load SUCCESS")
            print(" [!] START_EPOCH is ", start_epoch)
        else:
            start_epoch = 1
            counter = 1
            print(" [!] Load failed...")

        # loop for epoch
        start_time = time.time()
        for epoch_loop in range(start_epoch, self.epoch + 1):

            CNN_losses = []
  
            epoch_start_time = time.time()
            shuffle_idxs = random.sample(range(0, self.train_x.shape[0]), self.train_x.shape[0])
            shuffled_set = self.train_x[shuffle_idxs]
            shuffled_label = self.train_y[shuffle_idxs]
    
            # get batch data
            for idx in range(self.num_batches_train):
                batch_x = shuffled_set[idx*self.batch_size:(idx+1)*self.batch_size]
#                 batch_x = np.array(seq.augment_images(np.array(batch_x,dtype = uint8)),dtype = float32)
                batch_y = shuffled_label[idx*self.batch_size:(idx+1)*self.batch_size].reshape(
                                        [self.batch_size, self.nb_class])
                

                # update D network
                _, summary_str, cnn_loss = self.sess.run([self.cnn_optim, self.loss_sum, self.loss_cross_entropy],
                                               feed_dict={self.x: batch_x,
                                                          self.y: batch_y,
                                                          self.keep_prob: 0.5}
                                                      )
                self.writer.add_summary(summary_str, counter)

                CNN_losses.append(cnn_loss)

                # display training status            
                counter += 1
                print("Epoch: [%2d] [%4d/%4d] time: %4.4f, loss: %.8f" % (epoch_loop, idx, 
                                                                                    self.num_batches_train, 
                                                                          time.time() - start_time, cnn_loss))

            # After an epoch
            # Evaluates accuracy on test set
            test_accuracy_list = []
            for idx_test in range(self.num_batches_test):
                rand_index = np.random.choice(len(self.train_x), size=batch_size)
                batch_x_test = self.test_x[idx_test*self.batch_size:(idx_test+1)*self.batch_size]
                batch_y_tes = self.test_y[idx_test*self.batch_size:(idx_test+1)*self.batch_size].reshape(
                                        [self.batch_size, self.nb_class])
                accuracy = self.sess.run([self.accuracy],feed_dict={self.x: batch_x_test, 
                                                                   self.y: batch_y_tes,
                                                                   self.keep_prob: 1.0})
                test_accuracy_list.append(accuracy)
            test_accuracy = np.sum(test_accuracy_list)/self.num_batches_test
            
            #update learning rate
            _, rate = sess.run([self.add_global, self.lr])
                
            epoch_end_time = time.time()
            per_epoch_ptime = epoch_end_time - epoch_start_time
            
            print('[%d/%d] - ptime: %.4f loss: %.8f acc: %.5f lr: %.8f'% (epoch_loop, self.epoch, per_epoch_ptime, 
                                                                    np.mean(CNN_losses), test_accuracy, rate))
            self.train_hist['losses'].append(np.mean(CNN_losses))
            self.train_hist['accuracy'].append(test_accuracy)
            self.train_hist['learning_rate'].append(rate)
            self.train_hist['per_epoch_ptimes'].append(per_epoch_ptime)
            
            # save model
            self.save(self.checkpoint_dir, epoch_loop)
            
            # save trainhist for train
            f = open(self.trainhist_dir + '/' + self.model_name + '_train_hist.pkl', 'wb') 
            pickle.dump(self.train_hist, f)
            f.close()
            self.show_train_hist(self.train_hist, save=True, path= self.trainhist_dir + '/' 
                                 + self.model_name + '_train_hist.png')

        end_time = time.time()
        total_ptime = end_time - start_time
        self.train_hist['total_ptime'].append(total_ptime)
        print('Avg per epoch ptime: %.2f, total %d epochs ptime: %.2f' % (np.mean(self.train_hist['per_epoch_ptimes']), 
                                                                          self.epoch, total_ptime))
        print(" [*] Training finished!")
    
        """test after train"""
        best_acc = max(self.train_hist['accuracy'])
        beat_epoch = self.train_hist['accuracy'].index(best_acc) + 1
        print (" [*] Best Epoch: ", beat_epoch, ", Accuracy: ", best_acc)
        path_model = self.checkpoint_dir + '/' + self.model_name + '/'+ self.model_name +'-'+ str(beat_epoch)

        """ restore epoch """
        new_saver = tf.train.import_meta_graph(path_model + '.meta' )
        new_saver.restore(self.sess,path_model)

        # Evaluates accuracy on test set
        test_accuracy_list = []
        for idx_test in range(self.num_batches_test):
            batch_x_test = self.test_x[idx_test*self.batch_size:(idx_test+1)*self.batch_size]
            batch_y_tes = self.test_y[idx_test*self.batch_size:(idx_test+1)*self.batch_size].reshape(
                                    [self.batch_size, self.nb_class])
            accuracy = self.sess.run([self.accuracy],feed_dict={self.x: batch_x_test, 
                                                               self.y: batch_y_tes,
                                                               self.keep_prob: 1.0})
            test_accuracy_list.append(accuracy)
        test_accuracy = np.sum(test_accuracy_list)/self.num_batches_test
        print(" [*] Finished testing Best Epoch:", beat_epoch, ", accuracy: ",test_accuracy, "!")
        
    def test(self, epoch):
        path_model = self.checkpoint_dir + '/' + self.model_name + '/'+ self.model_name +'-'+ str(epoch)

        """ restore epoch """
        new_saver = tf.train.import_meta_graph(path_model + '.meta' )
        new_saver.restore(self.sess,path_model)

        # Evaluates accuracy on test set
        test_accuracy_list = []
        for idx_test in range(self.num_batches_test):
            batch_x_test = self.test_x[idx_test*self.batch_size:(idx_test+1)*self.batch_size]
            batch_y_tes = self.test_y[idx_test*self.batch_size:(idx_test+1)*self.batch_size].reshape(
                                    [self.batch_size, self.nb_class])
            accuracy = self.sess.run([self.accuracy],feed_dict={self.x: batch_x_test, 
                                                               self.y: batch_y_tes,
                                                               self.keep_prob: 1.0})
            test_accuracy_list.append(accuracy)
        test_accuracy = np.sum(test_accuracy_list)/self.num_batches_test
        print(" [*] Finished testing Epoch:", epoch, ", accuracy: ",test_accuracy, "!")
        
    def show_all_variables(self):
        model_vars = tf.trainable_variables()
        tf.contrib.slim.model_analyzer.analyze_vars(model_vars, print_info=True) 

    def save(self, checkpoint_dir, step):
        checkpoint_dir = os.path.join(checkpoint_dir, self.model_name)

        if not os.path.exists(checkpoint_dir):
            os.makedirs(checkpoint_dir)

        self.saver.save(self.sess,os.path.join(checkpoint_dir, self.model_name), global_step=step)

    def load(self, checkpoint_dir):
        import re
        print(" [*] Reading checkpoints...")
        checkpoint_dir = os.path.join(checkpoint_dir, self.model_name)

        ckpt = tf.train.get_checkpoint_state(checkpoint_dir)
        if ckpt and ckpt.model_checkpoint_path:
            ckpt_name = os.path.basename(ckpt.model_checkpoint_path)
            self.saver.restore(self.sess, os.path.join(checkpoint_dir, ckpt_name))
            epoch = int(next(re.finditer("(\d+)(?!.*\d)",ckpt_name)).group(0))
            print(" [*] Success to read [{}], epoch [{}]".format(ckpt_name,epoch))
            return True, epoch
        else:
            print(" [*] Failed to find a checkpoint")
            return False, 0
        
    def show_train_hist(self, hist, show = False, save = False, path = 'Train_hist.png'):
        x = range(1, len(hist['losses'])+1)

        y1 = hist['losses']
        y2 = hist['accuracy']
        
        fig, ax1 = plt.subplots()
                            
        ax2 = ax1.twinx()  

        ax1.plot(x, y1, 'b')
        ax2.plot(x, y2, 'r')
                            
        ax1.set_xlabel('Epoch')
                            
        ax1.set_ylabel('CNN_loss')    
        ax2.set_ylabel('accuracy')
                          
        plt.grid(True)
        plt.tight_layout()

        if save:
            plt.savefig(path, dpi = 400)

        if show:
            plt.show()
        else:
            plt.close()
   

In [5]:
gan_type = 'CNN'
dataset = '4_Flowers'
epoch = 50
batch_size = 80
checkpoint_dir = 'checkpoint'
log_dir = 'logs'
trainhist_dir = 'trainhist'

if not os.path.exists(checkpoint_dir):
        os.makedirs(checkpoint_dir)

# --log_dir
if not os.path.exists(log_dir):
    os.makedirs(log_dir)
    
# --trainhist_dir
if not os.path.exists(trainhist_dir):
    os.makedirs(trainhist_dir)

# open session
with tf.Session(config=tf.ConfigProto(allow_soft_placement=True)) as sess:
    
    # declare instance for GAN
    CNN = CNN(sess, epoch=epoch, batch_size=batch_size, dataset_name=dataset, checkpoint_dir=checkpoint_dir, 
                log_dir=log_dir, trainhist_dir=trainhist_dir)

    # build graph
    CNN.build_model()

    # show network architecture
    CNN.show_all_variables()

    # launch the graph in a session
    CNN.train()
    
    #CNN.test(epoch)
        
sess.close()
        

# lrdecay
# Avg per epoch ptime: 36.92, total 50 epochs ptime: 1705.18
#  [*] Training finished!
#  [*] Best Epoch:  34 , Accuracy:  0.987500011920929
# INFO:tensorflow:Restoring parameters from checkpoint/CNN_C5_D1_Kernel(3,3)_128_lrdecay0.0001/CNN_C5_D1_Kernel(3,3)_128_lrdecay0.0001-34
#  [*] Finished testing Best Epoch: 34 , accuracy:  0.987500011920929 !

Training: 16000
CNN:x (80, 128, 128, 3)
CNN: (80, 128, 128, 32)
CNN: (80, 64, 64, 32)
CNN: (80, 64, 64, 64)
CNN: (80, 32, 32, 64)
CNN: (80, 32, 32, 64)
CNN: (80, 16, 16, 64)
CNN: (80, 16, 16, 64)
CNN: (80, 8, 8, 64)
CNN: (80, 8, 8, 128)
CNN: (80, 4, 4, 128)
CNN: (80, 2048)
CNN:out_logit (80, 4)
------------------------
CNN:x (80, 128, 128, 3)
CNN: (80, 128, 128, 32)
CNN: (80, 64, 64, 32)
CNN: (80, 64, 64, 64)
CNN: (80, 32, 32, 64)
CNN: (80, 32, 32, 64)
CNN: (80, 16, 16, 64)
CNN: (80, 16, 16, 64)
CNN: (80, 8, 8, 64)
CNN: (80, 8, 8, 128)
CNN: (80, 4, 4, 128)
CNN: (80, 2048)
CNN:out_logit (80, 4)
------------------------
---------
Variables: name (type shape) [size]
---------
cnn/conv_1/kernel:0 (float32_ref 3x3x3x32) [864, bytes: 3456]
cnn/conv_1/bias:0 (float32_ref 32) [32, bytes: 128]
cnn/batch_normalization/beta:0 (float32_ref 32) [32, bytes: 128]
cnn/batch_normalization/gamma:0 (float32_ref 32) [32, bytes: 128]
cnn/conv_2/kernel:0 (float32_ref 3x3x32x64) [18432, bytes: 73728]
cnn/con

Epoch: [ 5] [ 102/ 200] time: 36.8016, loss: 0.16490085
Epoch: [ 5] [ 103/ 200] time: 36.9168, loss: 0.07413154
Epoch: [ 5] [ 104/ 200] time: 37.0328, loss: 0.26520473
Epoch: [ 5] [ 105/ 200] time: 37.1489, loss: 0.10467964
Epoch: [ 5] [ 106/ 200] time: 37.2646, loss: 0.08261442
Epoch: [ 5] [ 107/ 200] time: 37.3800, loss: 0.14797004
Epoch: [ 5] [ 108/ 200] time: 37.4966, loss: 0.10059147
Epoch: [ 5] [ 109/ 200] time: 37.6131, loss: 0.13054016
Epoch: [ 5] [ 110/ 200] time: 37.7309, loss: 0.05963375
Epoch: [ 5] [ 111/ 200] time: 37.8465, loss: 0.08337682
Epoch: [ 5] [ 112/ 200] time: 37.9625, loss: 0.19345482
Epoch: [ 5] [ 113/ 200] time: 38.0777, loss: 0.04302901
Epoch: [ 5] [ 114/ 200] time: 38.1936, loss: 0.13725203
Epoch: [ 5] [ 115/ 200] time: 38.3091, loss: 0.08817678
Epoch: [ 5] [ 116/ 200] time: 38.4250, loss: 0.07349065
Epoch: [ 5] [ 117/ 200] time: 38.5408, loss: 0.12450475
Epoch: [ 5] [ 118/ 200] time: 38.6585, loss: 0.06831111
Epoch: [ 5] [ 119/ 200] time: 38.7739, loss: 0.1

Epoch: [ 6] [  49/ 200] time: 76.2763, loss: 0.15801729
Epoch: [ 6] [  50/ 200] time: 76.3929, loss: 0.22229302
Epoch: [ 6] [  51/ 200] time: 76.5089, loss: 0.34561703
Epoch: [ 6] [  52/ 200] time: 76.6269, loss: 0.17468020
Epoch: [ 6] [  53/ 200] time: 76.7454, loss: 0.07443552
Epoch: [ 6] [  54/ 200] time: 76.8625, loss: 0.07273197
Epoch: [ 6] [  55/ 200] time: 76.9788, loss: 0.12462664
Epoch: [ 6] [  56/ 200] time: 77.0943, loss: 0.16983233
Epoch: [ 6] [  57/ 200] time: 77.2105, loss: 0.06709906
Epoch: [ 6] [  58/ 200] time: 77.6471, loss: 0.08032183
Epoch: [ 6] [  59/ 200] time: 77.7641, loss: 0.12667488
Epoch: [ 6] [  60/ 200] time: 77.8810, loss: 0.05577074
Epoch: [ 6] [  61/ 200] time: 77.9978, loss: 0.15971477
Epoch: [ 6] [  62/ 200] time: 78.1145, loss: 0.11381277
Epoch: [ 6] [  63/ 200] time: 78.2308, loss: 0.05456685
Epoch: [ 6] [  64/ 200] time: 78.3466, loss: 0.06746010
Epoch: [ 6] [  65/ 200] time: 78.4627, loss: 0.08504163
Epoch: [ 6] [  66/ 200] time: 78.5788, loss: 0.1

Epoch: [ 6] [ 197/ 200] time: 93.8305, loss: 0.05026470
Epoch: [ 6] [ 198/ 200] time: 93.9460, loss: 0.03322686
Epoch: [ 6] [ 199/ 200] time: 94.0622, loss: 0.06946547
[6/50] - ptime: 44.7494 loss: 0.10415764 acc: 0.95625 lr: 0.00094868
Epoch: [ 7] [   0/ 200] time: 111.6061, loss: 0.04215338
Epoch: [ 7] [   1/ 200] time: 111.7345, loss: 0.07782384
Epoch: [ 7] [   2/ 200] time: 111.8497, loss: 0.03000902
Epoch: [ 7] [   3/ 200] time: 111.9659, loss: 0.05931564
Epoch: [ 7] [   4/ 200] time: 112.0805, loss: 0.04285492
Epoch: [ 7] [   5/ 200] time: 112.1951, loss: 0.15187150
Epoch: [ 7] [   6/ 200] time: 112.3193, loss: 0.06208193
Epoch: [ 7] [   7/ 200] time: 112.4433, loss: 0.08941506
Epoch: [ 7] [   8/ 200] time: 112.5615, loss: 0.07987471
Epoch: [ 7] [   9/ 200] time: 112.6785, loss: 0.17487139
Epoch: [ 7] [  10/ 200] time: 112.7934, loss: 0.07873712
Epoch: [ 7] [  11/ 200] time: 112.9090, loss: 0.11405486
Epoch: [ 7] [  12/ 200] time: 113.0295, loss: 0.08221831
Epoch: [ 7] [  13/ 200

Epoch: [ 7] [ 141/ 200] time: 128.2781, loss: 0.05481354
Epoch: [ 7] [ 142/ 200] time: 128.3933, loss: 0.07310781
Epoch: [ 7] [ 143/ 200] time: 128.5094, loss: 0.10423486
Epoch: [ 7] [ 144/ 200] time: 128.6261, loss: 0.05991151
Epoch: [ 7] [ 145/ 200] time: 128.7425, loss: 0.07879257
Epoch: [ 7] [ 146/ 200] time: 128.8588, loss: 0.08339653
Epoch: [ 7] [ 147/ 200] time: 128.9765, loss: 0.04710919
Epoch: [ 7] [ 148/ 200] time: 129.0929, loss: 0.16696872
Epoch: [ 7] [ 149/ 200] time: 129.2092, loss: 0.18328425
Epoch: [ 7] [ 150/ 200] time: 129.3247, loss: 0.04835571
Epoch: [ 7] [ 151/ 200] time: 129.4408, loss: 0.12370223
Epoch: [ 7] [ 152/ 200] time: 129.5564, loss: 0.19229588
Epoch: [ 7] [ 153/ 200] time: 129.6736, loss: 0.10797641
Epoch: [ 7] [ 154/ 200] time: 129.7895, loss: 0.06471463
Epoch: [ 7] [ 155/ 200] time: 129.9068, loss: 0.07567247
Epoch: [ 7] [ 156/ 200] time: 130.0230, loss: 0.05810273
Epoch: [ 7] [ 157/ 200] time: 130.1390, loss: 0.11630239
Epoch: [ 7] [ 158/ 200] time: 1

Epoch: [ 8] [  84/ 200] time: 163.7716, loss: 0.11422889
Epoch: [ 8] [  85/ 200] time: 163.8873, loss: 0.08089671
Epoch: [ 8] [  86/ 200] time: 164.0035, loss: 0.05800308
Epoch: [ 8] [  87/ 200] time: 164.1187, loss: 0.02571313
Epoch: [ 8] [  88/ 200] time: 164.2355, loss: 0.10581694
Epoch: [ 8] [  89/ 200] time: 164.3523, loss: 0.08363896
Epoch: [ 8] [  90/ 200] time: 164.4685, loss: 0.14833781
Epoch: [ 8] [  91/ 200] time: 164.5867, loss: 0.05125754
Epoch: [ 8] [  92/ 200] time: 164.7029, loss: 0.20845824
Epoch: [ 8] [  93/ 200] time: 164.8185, loss: 0.13956285
Epoch: [ 8] [  94/ 200] time: 164.9347, loss: 0.07572806
Epoch: [ 8] [  95/ 200] time: 165.0513, loss: 0.07869139
Epoch: [ 8] [  96/ 200] time: 165.1672, loss: 0.09347650
Epoch: [ 8] [  97/ 200] time: 165.2829, loss: 0.07867461
Epoch: [ 8] [  98/ 200] time: 165.3990, loss: 0.03993009
Epoch: [ 8] [  99/ 200] time: 165.5163, loss: 0.09337362
Epoch: [ 8] [ 100/ 200] time: 165.6336, loss: 0.13038591
Epoch: [ 8] [ 101/ 200] time: 1

Epoch: [ 9] [  28/ 200] time: 200.9054, loss: 0.05456484
Epoch: [ 9] [  29/ 200] time: 201.0221, loss: 0.22306709
Epoch: [ 9] [  30/ 200] time: 201.1389, loss: 0.04581181
Epoch: [ 9] [  31/ 200] time: 201.2548, loss: 0.03264774
Epoch: [ 9] [  32/ 200] time: 201.3709, loss: 0.04419853
Epoch: [ 9] [  33/ 200] time: 201.4869, loss: 0.03351296
Epoch: [ 9] [  34/ 200] time: 201.6037, loss: 0.05401257
Epoch: [ 9] [  35/ 200] time: 201.7196, loss: 0.01632962
Epoch: [ 9] [  36/ 200] time: 201.8366, loss: 0.04560484
Epoch: [ 9] [  37/ 200] time: 201.9527, loss: 0.05002270
Epoch: [ 9] [  38/ 200] time: 202.0699, loss: 0.12078371
Epoch: [ 9] [  39/ 200] time: 202.1865, loss: 0.06517749
Epoch: [ 9] [  40/ 200] time: 202.3028, loss: 0.04052268
Epoch: [ 9] [  41/ 200] time: 202.4185, loss: 0.04381040
Epoch: [ 9] [  42/ 200] time: 202.5357, loss: 0.06598445
Epoch: [ 9] [  43/ 200] time: 202.6520, loss: 0.13078982
Epoch: [ 9] [  44/ 200] time: 202.7685, loss: 0.04464499
Epoch: [ 9] [  45/ 200] time: 2

Epoch: [ 9] [ 172/ 200] time: 217.7149, loss: 0.05823259
Epoch: [ 9] [ 173/ 200] time: 217.8308, loss: 0.01715049
Epoch: [ 9] [ 174/ 200] time: 217.9474, loss: 0.05114489
Epoch: [ 9] [ 175/ 200] time: 218.0637, loss: 0.06251244
Epoch: [ 9] [ 176/ 200] time: 218.1820, loss: 0.08957618
Epoch: [ 9] [ 177/ 200] time: 218.2985, loss: 0.08076546
Epoch: [ 9] [ 178/ 200] time: 218.4160, loss: 0.05187222
Epoch: [ 9] [ 179/ 200] time: 218.5318, loss: 0.06013948
Epoch: [ 9] [ 180/ 200] time: 218.6498, loss: 0.07966654
Epoch: [ 9] [ 181/ 200] time: 218.7657, loss: 0.06370400
Epoch: [ 9] [ 182/ 200] time: 218.8829, loss: 0.16447519
Epoch: [ 9] [ 183/ 200] time: 218.9989, loss: 0.08193421
Epoch: [ 9] [ 184/ 200] time: 219.1154, loss: 0.02939069
Epoch: [ 9] [ 185/ 200] time: 219.2354, loss: 0.01274443
Epoch: [ 9] [ 186/ 200] time: 219.3531, loss: 0.10107967
Epoch: [ 9] [ 187/ 200] time: 219.4692, loss: 0.04481843
Epoch: [ 9] [ 188/ 200] time: 219.5856, loss: 0.10793616
Epoch: [ 9] [ 189/ 200] time: 2

Epoch: [10] [ 116/ 200] time: 255.5559, loss: 0.03110703
Epoch: [10] [ 117/ 200] time: 255.6731, loss: 0.08186444
Epoch: [10] [ 118/ 200] time: 255.7894, loss: 0.07002605
Epoch: [10] [ 119/ 200] time: 255.9053, loss: 0.04396880
Epoch: [10] [ 120/ 200] time: 256.0219, loss: 0.02415152
Epoch: [10] [ 121/ 200] time: 256.1376, loss: 0.07357559
Epoch: [10] [ 122/ 200] time: 256.2542, loss: 0.03887983
Epoch: [10] [ 123/ 200] time: 256.3708, loss: 0.09569345
Epoch: [10] [ 124/ 200] time: 256.4878, loss: 0.02116451
Epoch: [10] [ 125/ 200] time: 256.6049, loss: 0.03706606
Epoch: [10] [ 126/ 200] time: 256.7217, loss: 0.05032840
Epoch: [10] [ 127/ 200] time: 256.8378, loss: 0.03830501
Epoch: [10] [ 128/ 200] time: 256.9549, loss: 0.04628962
Epoch: [10] [ 129/ 200] time: 257.0705, loss: 0.02851276
Epoch: [10] [ 130/ 200] time: 257.1871, loss: 0.07527606
Epoch: [10] [ 131/ 200] time: 257.3041, loss: 0.02302452
Epoch: [10] [ 132/ 200] time: 257.4213, loss: 0.19977780
Epoch: [10] [ 133/ 200] time: 2

Epoch: [11] [  60/ 200] time: 288.7212, loss: 0.02649247
Epoch: [11] [  61/ 200] time: 288.8370, loss: 0.02843194
Epoch: [11] [  62/ 200] time: 288.9541, loss: 0.06656607
Epoch: [11] [  63/ 200] time: 289.0705, loss: 0.06211658
Epoch: [11] [  64/ 200] time: 289.1870, loss: 0.04160196
Epoch: [11] [  65/ 200] time: 289.3027, loss: 0.02521286
Epoch: [11] [  66/ 200] time: 289.4197, loss: 0.02167942
Epoch: [11] [  67/ 200] time: 289.5357, loss: 0.05666419
Epoch: [11] [  68/ 200] time: 289.6542, loss: 0.03435690
Epoch: [11] [  69/ 200] time: 289.7702, loss: 0.03950231
Epoch: [11] [  70/ 200] time: 289.8865, loss: 0.09105529
Epoch: [11] [  71/ 200] time: 290.0028, loss: 0.04237801
Epoch: [11] [  72/ 200] time: 290.1199, loss: 0.06062915
Epoch: [11] [  73/ 200] time: 290.2358, loss: 0.02039002
Epoch: [11] [  74/ 200] time: 290.3530, loss: 0.05577037
Epoch: [11] [  75/ 200] time: 290.4698, loss: 0.02990337
Epoch: [11] [  76/ 200] time: 290.5864, loss: 0.01045491
Epoch: [11] [  77/ 200] time: 2

Epoch: [12] [   4/ 200] time: 315.3321, loss: 0.05779972
Epoch: [12] [   5/ 200] time: 315.4484, loss: 0.08644362
Epoch: [12] [   6/ 200] time: 315.5658, loss: 0.02896317
Epoch: [12] [   7/ 200] time: 315.6824, loss: 0.04200263
Epoch: [12] [   8/ 200] time: 315.7993, loss: 0.03299222
Epoch: [12] [   9/ 200] time: 315.9161, loss: 0.06612179
Epoch: [12] [  10/ 200] time: 316.0356, loss: 0.01674898
Epoch: [12] [  11/ 200] time: 316.1531, loss: 0.00297415
Epoch: [12] [  12/ 200] time: 316.2699, loss: 0.01639431
Epoch: [12] [  13/ 200] time: 316.3859, loss: 0.03203345
Epoch: [12] [  14/ 200] time: 316.5026, loss: 0.04609541
Epoch: [12] [  15/ 200] time: 316.6205, loss: 0.01705113
Epoch: [12] [  16/ 200] time: 316.7366, loss: 0.02823653
Epoch: [12] [  17/ 200] time: 316.8535, loss: 0.00146199
Epoch: [12] [  18/ 200] time: 316.9714, loss: 0.01463243
Epoch: [12] [  19/ 200] time: 317.0893, loss: 0.00987022
Epoch: [12] [  20/ 200] time: 317.2061, loss: 0.02548057
Epoch: [12] [  21/ 200] time: 3

Epoch: [12] [ 148/ 200] time: 332.1557, loss: 0.04024732
Epoch: [12] [ 149/ 200] time: 332.2715, loss: 0.10257804
Epoch: [12] [ 150/ 200] time: 332.3880, loss: 0.03115837
Epoch: [12] [ 151/ 200] time: 332.5044, loss: 0.03369526
Epoch: [12] [ 152/ 200] time: 332.6221, loss: 0.02232183
Epoch: [12] [ 153/ 200] time: 332.7380, loss: 0.05568088
Epoch: [12] [ 154/ 200] time: 332.8542, loss: 0.11409089
Epoch: [12] [ 155/ 200] time: 332.9707, loss: 0.01317375
Epoch: [12] [ 156/ 200] time: 333.0881, loss: 0.02335308
Epoch: [12] [ 157/ 200] time: 333.2038, loss: 0.10679454
Epoch: [12] [ 158/ 200] time: 333.3200, loss: 0.13338575
Epoch: [12] [ 159/ 200] time: 333.4361, loss: 0.03383457
Epoch: [12] [ 160/ 200] time: 333.5527, loss: 0.05450901
Epoch: [12] [ 161/ 200] time: 333.6700, loss: 0.02583797
Epoch: [12] [ 162/ 200] time: 333.7866, loss: 0.03101752
Epoch: [12] [ 163/ 200] time: 333.9026, loss: 0.03988383
Epoch: [12] [ 164/ 200] time: 334.0206, loss: 0.03827398
Epoch: [12] [ 165/ 200] time: 3

Epoch: [13] [  92/ 200] time: 367.0640, loss: 0.02123121
Epoch: [13] [  93/ 200] time: 367.1801, loss: 0.04577254
Epoch: [13] [  94/ 200] time: 367.2978, loss: 0.01795110
Epoch: [13] [  95/ 200] time: 367.4139, loss: 0.01645010
Epoch: [13] [  96/ 200] time: 367.5308, loss: 0.01814470
Epoch: [13] [  97/ 200] time: 367.6480, loss: 0.07432470
Epoch: [13] [  98/ 200] time: 367.7647, loss: 0.10926767
Epoch: [13] [  99/ 200] time: 367.8807, loss: 0.07698718
Epoch: [13] [ 100/ 200] time: 367.9968, loss: 0.06373218
Epoch: [13] [ 101/ 200] time: 368.1127, loss: 0.02047083
Epoch: [13] [ 102/ 200] time: 368.2298, loss: 0.02404613
Epoch: [13] [ 103/ 200] time: 368.3457, loss: 0.07649013
Epoch: [13] [ 104/ 200] time: 368.4622, loss: 0.07263810
Epoch: [13] [ 105/ 200] time: 368.5804, loss: 0.02709202
Epoch: [13] [ 106/ 200] time: 368.6985, loss: 0.03472199
Epoch: [13] [ 107/ 200] time: 368.8152, loss: 0.02808200
Epoch: [13] [ 108/ 200] time: 368.9321, loss: 0.01217973
Epoch: [13] [ 109/ 200] time: 3

Epoch: [14] [  36/ 200] time: 400.3862, loss: 0.03670070
Epoch: [14] [  37/ 200] time: 400.5849, loss: 0.01368448
Epoch: [14] [  38/ 200] time: 400.7019, loss: 0.01424319
Epoch: [14] [  39/ 200] time: 400.8183, loss: 0.08883981
Epoch: [14] [  40/ 200] time: 400.9348, loss: 0.00912047
Epoch: [14] [  41/ 200] time: 401.0542, loss: 0.05192358
Epoch: [14] [  42/ 200] time: 401.1715, loss: 0.00193939
Epoch: [14] [  43/ 200] time: 401.2878, loss: 0.01181303
Epoch: [14] [  44/ 200] time: 401.4049, loss: 0.01591582
Epoch: [14] [  45/ 200] time: 401.5212, loss: 0.00903623
Epoch: [14] [  46/ 200] time: 401.6391, loss: 0.09718104
Epoch: [14] [  47/ 200] time: 401.7550, loss: 0.03306454
Epoch: [14] [  48/ 200] time: 401.8720, loss: 0.00756304
Epoch: [14] [  49/ 200] time: 401.9901, loss: 0.02296482
Epoch: [14] [  50/ 200] time: 402.1069, loss: 0.07920284
Epoch: [14] [  51/ 200] time: 402.2227, loss: 0.02000144
Epoch: [14] [  52/ 200] time: 402.3391, loss: 0.01327300
Epoch: [14] [  53/ 200] time: 4

Epoch: [14] [ 180/ 200] time: 417.2895, loss: 0.00503539
Epoch: [14] [ 181/ 200] time: 417.4057, loss: 0.01486074
Epoch: [14] [ 182/ 200] time: 417.5225, loss: 0.03392984
Epoch: [14] [ 183/ 200] time: 417.6396, loss: 0.03166569
Epoch: [14] [ 184/ 200] time: 417.7564, loss: 0.02332544
Epoch: [14] [ 185/ 200] time: 417.8725, loss: 0.02691422
Epoch: [14] [ 186/ 200] time: 417.9895, loss: 0.02003771
Epoch: [14] [ 187/ 200] time: 418.1062, loss: 0.02340805
Epoch: [14] [ 188/ 200] time: 418.2237, loss: 0.06904849
Epoch: [14] [ 189/ 200] time: 418.3409, loss: 0.05095688
Epoch: [14] [ 190/ 200] time: 418.4573, loss: 0.02986784
Epoch: [14] [ 191/ 200] time: 418.5742, loss: 0.00883709
Epoch: [14] [ 192/ 200] time: 418.6912, loss: 0.06286784
Epoch: [14] [ 193/ 200] time: 418.8072, loss: 0.01131590
Epoch: [14] [ 194/ 200] time: 418.9235, loss: 0.00120943
Epoch: [14] [ 195/ 200] time: 419.0409, loss: 0.02996031
Epoch: [14] [ 196/ 200] time: 419.1576, loss: 0.03755628
Epoch: [14] [ 197/ 200] time: 4

Epoch: [15] [ 124/ 200] time: 449.8274, loss: 0.00692758
Epoch: [15] [ 125/ 200] time: 449.9431, loss: 0.00798259
Epoch: [15] [ 126/ 200] time: 450.0618, loss: 0.01000143
Epoch: [15] [ 127/ 200] time: 450.1785, loss: 0.01278185
Epoch: [15] [ 128/ 200] time: 450.2948, loss: 0.03464708
Epoch: [15] [ 129/ 200] time: 450.4107, loss: 0.01417730
Epoch: [15] [ 130/ 200] time: 450.5271, loss: 0.01604271
Epoch: [15] [ 131/ 200] time: 450.6443, loss: 0.02962562
Epoch: [15] [ 132/ 200] time: 450.7609, loss: 0.01422254
Epoch: [15] [ 133/ 200] time: 450.8769, loss: 0.00418569
Epoch: [15] [ 134/ 200] time: 450.9934, loss: 0.01482442
Epoch: [15] [ 135/ 200] time: 451.1093, loss: 0.03599935
Epoch: [15] [ 136/ 200] time: 451.2258, loss: 0.01974088
Epoch: [15] [ 137/ 200] time: 451.3424, loss: 0.04103851
Epoch: [15] [ 138/ 200] time: 451.4592, loss: 0.04079866
Epoch: [15] [ 139/ 200] time: 451.5754, loss: 0.04384184
Epoch: [15] [ 140/ 200] time: 451.6925, loss: 0.01698554
Epoch: [15] [ 141/ 200] time: 4

Epoch: [16] [  68/ 200] time: 481.2230, loss: 0.00449379
Epoch: [16] [  69/ 200] time: 481.3391, loss: 0.01195321
Epoch: [16] [  70/ 200] time: 481.4556, loss: 0.01331282
Epoch: [16] [  71/ 200] time: 481.5722, loss: 0.01871671
Epoch: [16] [  72/ 200] time: 481.6895, loss: 0.07067208
Epoch: [16] [  73/ 200] time: 481.8065, loss: 0.00200250
Epoch: [16] [  74/ 200] time: 481.9234, loss: 0.02018421
Epoch: [16] [  75/ 200] time: 482.0404, loss: 0.02262016
Epoch: [16] [  76/ 200] time: 482.1569, loss: 0.04520422
Epoch: [16] [  77/ 200] time: 482.2730, loss: 0.01291741
Epoch: [16] [  78/ 200] time: 482.3899, loss: 0.04282779
Epoch: [16] [  79/ 200] time: 482.5064, loss: 0.01138076
Epoch: [16] [  80/ 200] time: 482.6239, loss: 0.01834410
Epoch: [16] [  81/ 200] time: 482.7401, loss: 0.01206991
Epoch: [16] [  82/ 200] time: 482.8566, loss: 0.01820371
Epoch: [16] [  83/ 200] time: 482.9731, loss: 0.01659061
Epoch: [16] [  84/ 200] time: 483.0907, loss: 0.00119450
Epoch: [16] [  85/ 200] time: 4

Epoch: [17] [  12/ 200] time: 512.4837, loss: 0.01579804
Epoch: [17] [  13/ 200] time: 512.6033, loss: 0.01036007
Epoch: [17] [  14/ 200] time: 512.7210, loss: 0.01639195
Epoch: [17] [  15/ 200] time: 512.8380, loss: 0.00086191
Epoch: [17] [  16/ 200] time: 512.9549, loss: 0.02512766
Epoch: [17] [  17/ 200] time: 513.0716, loss: 0.01735094
Epoch: [17] [  18/ 200] time: 513.1883, loss: 0.00076381
Epoch: [17] [  19/ 200] time: 513.3058, loss: 0.00664136
Epoch: [17] [  20/ 200] time: 513.4227, loss: 0.00591641
Epoch: [17] [  21/ 200] time: 513.5396, loss: 0.01115132
Epoch: [17] [  22/ 200] time: 513.6584, loss: 0.00850483
Epoch: [17] [  23/ 200] time: 513.7773, loss: 0.00498112
Epoch: [17] [  24/ 200] time: 513.8944, loss: 0.01752915
Epoch: [17] [  25/ 200] time: 514.0111, loss: 0.02886571
Epoch: [17] [  26/ 200] time: 514.1284, loss: 0.00730677
Epoch: [17] [  27/ 200] time: 514.2538, loss: 0.02603133
Epoch: [17] [  28/ 200] time: 514.3712, loss: 0.00239553
Epoch: [17] [  29/ 200] time: 5

Epoch: [17] [ 156/ 200] time: 529.3247, loss: 0.07495681
Epoch: [17] [ 157/ 200] time: 529.4414, loss: 0.04160335
Epoch: [17] [ 158/ 200] time: 529.5578, loss: 0.01428855
Epoch: [17] [ 159/ 200] time: 529.6751, loss: 0.04979153
Epoch: [17] [ 160/ 200] time: 529.7958, loss: 0.02502026
Epoch: [17] [ 161/ 200] time: 529.9113, loss: 0.02798611
Epoch: [17] [ 162/ 200] time: 530.0277, loss: 0.10621189
Epoch: [17] [ 163/ 200] time: 530.1437, loss: 0.00780978
Epoch: [17] [ 164/ 200] time: 530.2608, loss: 0.03184211
Epoch: [17] [ 165/ 200] time: 530.3766, loss: 0.01022129
Epoch: [17] [ 166/ 200] time: 530.4928, loss: 0.05545449
Epoch: [17] [ 167/ 200] time: 530.6100, loss: 0.01876684
Epoch: [17] [ 168/ 200] time: 530.7281, loss: 0.00761745
Epoch: [17] [ 169/ 200] time: 530.8442, loss: 0.04266273
Epoch: [17] [ 170/ 200] time: 530.9604, loss: 0.02237207
Epoch: [17] [ 171/ 200] time: 531.0768, loss: 0.05340824
Epoch: [17] [ 172/ 200] time: 531.1931, loss: 0.04622352
Epoch: [17] [ 173/ 200] time: 5

Epoch: [18] [ 100/ 200] time: 560.7981, loss: 0.00921386
Epoch: [18] [ 101/ 200] time: 560.9140, loss: 0.02866079
Epoch: [18] [ 102/ 200] time: 561.0305, loss: 0.01488282
Epoch: [18] [ 103/ 200] time: 561.1488, loss: 0.07048069
Epoch: [18] [ 104/ 200] time: 561.2654, loss: 0.05567127
Epoch: [18] [ 105/ 200] time: 561.3819, loss: 0.02219791
Epoch: [18] [ 106/ 200] time: 561.4984, loss: 0.01595198
Epoch: [18] [ 107/ 200] time: 561.6159, loss: 0.00570526
Epoch: [18] [ 108/ 200] time: 561.7324, loss: 0.00131595
Epoch: [18] [ 109/ 200] time: 561.8490, loss: 0.00431325
Epoch: [18] [ 110/ 200] time: 561.9655, loss: 0.00986758
Epoch: [18] [ 111/ 200] time: 562.0812, loss: 0.00965224
Epoch: [18] [ 112/ 200] time: 562.1995, loss: 0.03737512
Epoch: [18] [ 113/ 200] time: 562.3157, loss: 0.00196510
Epoch: [18] [ 114/ 200] time: 562.4321, loss: 0.02886613
Epoch: [18] [ 115/ 200] time: 562.5484, loss: 0.01979738
Epoch: [18] [ 116/ 200] time: 562.6657, loss: 0.01062181
Epoch: [18] [ 117/ 200] time: 5

Epoch: [19] [  44/ 200] time: 592.4322, loss: 0.01274441
Epoch: [19] [  45/ 200] time: 592.6799, loss: 0.00695257
Epoch: [19] [  46/ 200] time: 592.7944, loss: 0.01680494
Epoch: [19] [  47/ 200] time: 592.9119, loss: 0.05101282
Epoch: [19] [  48/ 200] time: 593.0274, loss: 0.00424309
Epoch: [19] [  49/ 200] time: 593.1417, loss: 0.00200537
Epoch: [19] [  50/ 200] time: 593.2592, loss: 0.07708754
Epoch: [19] [  51/ 200] time: 593.3845, loss: 0.01211568
Epoch: [19] [  52/ 200] time: 593.5091, loss: 0.02394114
Epoch: [19] [  53/ 200] time: 593.6289, loss: 0.00304969
Epoch: [19] [  54/ 200] time: 593.7460, loss: 0.07279751
Epoch: [19] [  55/ 200] time: 593.8630, loss: 0.00973365
Epoch: [19] [  56/ 200] time: 593.9802, loss: 0.03114822
Epoch: [19] [  57/ 200] time: 594.0979, loss: 0.01124749
Epoch: [19] [  58/ 200] time: 594.2151, loss: 0.00877972
Epoch: [19] [  59/ 200] time: 594.3339, loss: 0.00498800
Epoch: [19] [  60/ 200] time: 594.4501, loss: 0.00027032
Epoch: [19] [  61/ 200] time: 5

Epoch: [19] [ 189/ 200] time: 609.6540, loss: 0.04998655
Epoch: [19] [ 190/ 200] time: 609.7714, loss: 0.04763963
Epoch: [19] [ 191/ 200] time: 609.8891, loss: 0.00877621
Epoch: [19] [ 192/ 200] time: 610.0069, loss: 0.00368015
Epoch: [19] [ 193/ 200] time: 610.1241, loss: 0.00646949
Epoch: [19] [ 194/ 200] time: 610.2436, loss: 0.12202661
Epoch: [19] [ 195/ 200] time: 610.3642, loss: 0.00569812
Epoch: [19] [ 196/ 200] time: 610.4817, loss: 0.04319187
Epoch: [19] [ 197/ 200] time: 610.5999, loss: 0.02043673
Epoch: [19] [ 198/ 200] time: 610.7163, loss: 0.01736393
Epoch: [19] [ 199/ 200] time: 610.8341, loss: 0.00310715
[19/50] - ptime: 38.0137 loss: 0.01978709 acc: 0.97500 lr: 0.00081858
Epoch: [20] [   0/ 200] time: 613.0440, loss: 0.02756697
Epoch: [20] [   1/ 200] time: 613.1584, loss: 0.01375918
Epoch: [20] [   2/ 200] time: 613.2757, loss: 0.01257277
Epoch: [20] [   3/ 200] time: 613.3921, loss: 0.01251516
Epoch: [20] [   4/ 200] time: 613.5098, loss: 0.00857850
Epoch: [20] [   5/

Epoch: [20] [ 132/ 200] time: 628.4594, loss: 0.01793872
Epoch: [20] [ 133/ 200] time: 628.5770, loss: 0.01759235
Epoch: [20] [ 134/ 200] time: 628.6942, loss: 0.02190712
Epoch: [20] [ 135/ 200] time: 628.8104, loss: 0.01735709
Epoch: [20] [ 136/ 200] time: 628.9277, loss: 0.00168099
Epoch: [20] [ 137/ 200] time: 629.0437, loss: 0.02674973
Epoch: [20] [ 138/ 200] time: 629.1609, loss: 0.02651365
Epoch: [20] [ 139/ 200] time: 629.2769, loss: 0.00660778
Epoch: [20] [ 140/ 200] time: 629.3961, loss: 0.00743004
Epoch: [20] [ 141/ 200] time: 629.5125, loss: 0.00525197
Epoch: [20] [ 142/ 200] time: 629.6302, loss: 0.02827867
Epoch: [20] [ 143/ 200] time: 629.7462, loss: 0.03297330
Epoch: [20] [ 144/ 200] time: 629.8625, loss: 0.00817952
Epoch: [20] [ 145/ 200] time: 629.9785, loss: 0.01749435
Epoch: [20] [ 146/ 200] time: 630.0948, loss: 0.00881251
Epoch: [20] [ 147/ 200] time: 630.2106, loss: 0.00309059
Epoch: [20] [ 148/ 200] time: 630.3287, loss: 0.02605168
Epoch: [20] [ 149/ 200] time: 6

Epoch: [21] [  76/ 200] time: 660.6312, loss: 0.00842260
Epoch: [21] [  77/ 200] time: 660.7485, loss: 0.00534619
Epoch: [21] [  78/ 200] time: 660.8677, loss: 0.02459614
Epoch: [21] [  79/ 200] time: 660.9837, loss: 0.00108496
Epoch: [21] [  80/ 200] time: 661.1012, loss: 0.03532852
Epoch: [21] [  81/ 200] time: 661.2180, loss: 0.03542045
Epoch: [21] [  82/ 200] time: 661.3361, loss: 0.00270818
Epoch: [21] [  83/ 200] time: 661.4531, loss: 0.00529913
Epoch: [21] [  84/ 200] time: 661.5707, loss: 0.00030151
Epoch: [21] [  85/ 200] time: 661.6879, loss: 0.00166925
Epoch: [21] [  86/ 200] time: 661.8053, loss: 0.01772172
Epoch: [21] [  87/ 200] time: 661.9221, loss: 0.00170601
Epoch: [21] [  88/ 200] time: 662.0397, loss: 0.00050829
Epoch: [21] [  89/ 200] time: 662.1569, loss: 0.00545302
Epoch: [21] [  90/ 200] time: 662.2743, loss: 0.00367017
Epoch: [21] [  91/ 200] time: 662.3924, loss: 0.06868485
Epoch: [21] [  92/ 200] time: 662.5091, loss: 0.01019386
Epoch: [21] [  93/ 200] time: 6

Epoch: [22] [  20/ 200] time: 692.2271, loss: 0.03166995
Epoch: [22] [  21/ 200] time: 692.3442, loss: 0.01700986
Epoch: [22] [  22/ 200] time: 692.4607, loss: 0.01997662
Epoch: [22] [  23/ 200] time: 692.5775, loss: 0.12744460
Epoch: [22] [  24/ 200] time: 692.6952, loss: 0.03205011
Epoch: [22] [  25/ 200] time: 692.8122, loss: 0.01647967
Epoch: [22] [  26/ 200] time: 692.9299, loss: 0.01384688
Epoch: [22] [  27/ 200] time: 693.0462, loss: 0.03819185
Epoch: [22] [  28/ 200] time: 693.1634, loss: 0.04891366
Epoch: [22] [  29/ 200] time: 693.2805, loss: 0.09543807
Epoch: [22] [  30/ 200] time: 693.3980, loss: 0.03085785
Epoch: [22] [  31/ 200] time: 693.5153, loss: 0.01160190
Epoch: [22] [  32/ 200] time: 693.6338, loss: 0.00849540
Epoch: [22] [  33/ 200] time: 693.7518, loss: 0.00720857
Epoch: [22] [  34/ 200] time: 693.8687, loss: 0.08538775
Epoch: [22] [  35/ 200] time: 693.9849, loss: 0.01480733
Epoch: [22] [  36/ 200] time: 694.1025, loss: 0.03930867
Epoch: [22] [  37/ 200] time: 6

Epoch: [22] [ 164/ 200] time: 709.1586, loss: 0.00346242
Epoch: [22] [ 165/ 200] time: 709.2750, loss: 0.00215226
Epoch: [22] [ 166/ 200] time: 709.3926, loss: 0.00656210
Epoch: [22] [ 167/ 200] time: 709.5098, loss: 0.00457104
Epoch: [22] [ 168/ 200] time: 709.6299, loss: 0.01602372
Epoch: [22] [ 169/ 200] time: 709.7467, loss: 0.00611559
Epoch: [22] [ 170/ 200] time: 709.8634, loss: 0.01016102
Epoch: [22] [ 171/ 200] time: 709.9818, loss: 0.00948866
Epoch: [22] [ 172/ 200] time: 710.0992, loss: 0.02257865
Epoch: [22] [ 173/ 200] time: 710.2165, loss: 0.12009877
Epoch: [22] [ 174/ 200] time: 710.3331, loss: 0.04712471
Epoch: [22] [ 175/ 200] time: 710.4505, loss: 0.01569778
Epoch: [22] [ 176/ 200] time: 710.5668, loss: 0.06175947
Epoch: [22] [ 177/ 200] time: 710.6846, loss: 0.09481134
Epoch: [22] [ 178/ 200] time: 710.8023, loss: 0.01058604
Epoch: [22] [ 179/ 200] time: 710.9202, loss: 0.00749124
Epoch: [22] [ 180/ 200] time: 711.0379, loss: 0.00662918
Epoch: [22] [ 181/ 200] time: 7

Epoch: [23] [ 108/ 200] time: 740.3250, loss: 0.02735687
Epoch: [23] [ 109/ 200] time: 740.4422, loss: 0.01901179
Epoch: [23] [ 110/ 200] time: 740.5595, loss: 0.01467482
Epoch: [23] [ 111/ 200] time: 740.6775, loss: 0.00343358
Epoch: [23] [ 112/ 200] time: 740.7955, loss: 0.00739705
Epoch: [23] [ 113/ 200] time: 740.9125, loss: 0.02706455
Epoch: [23] [ 114/ 200] time: 741.0302, loss: 0.00306865
Epoch: [23] [ 115/ 200] time: 741.1476, loss: 0.03401753
Epoch: [23] [ 116/ 200] time: 741.2640, loss: 0.08621902
Epoch: [23] [ 117/ 200] time: 741.3818, loss: 0.02471527
Epoch: [23] [ 118/ 200] time: 741.4983, loss: 0.00151426
Epoch: [23] [ 119/ 200] time: 741.6164, loss: 0.02822450
Epoch: [23] [ 120/ 200] time: 741.7331, loss: 0.02495589
Epoch: [23] [ 121/ 200] time: 741.8502, loss: 0.00108022
Epoch: [23] [ 122/ 200] time: 741.9669, loss: 0.05388822
Epoch: [23] [ 123/ 200] time: 742.0835, loss: 0.00040330
Epoch: [23] [ 124/ 200] time: 742.2012, loss: 0.00516100
Epoch: [23] [ 125/ 200] time: 7

Epoch: [24] [  52/ 200] time: 772.1239, loss: 0.12430511
Epoch: [24] [  53/ 200] time: 772.2413, loss: 0.00096273
Epoch: [24] [  54/ 200] time: 772.3621, loss: 0.00754604
Epoch: [24] [  55/ 200] time: 772.4803, loss: 0.02216220
Epoch: [24] [  56/ 200] time: 772.5981, loss: 0.00323725
Epoch: [24] [  57/ 200] time: 772.7154, loss: 0.00012711
Epoch: [24] [  58/ 200] time: 772.8332, loss: 0.01857986
Epoch: [24] [  59/ 200] time: 772.9511, loss: 0.02463638
Epoch: [24] [  60/ 200] time: 773.0704, loss: 0.00695333
Epoch: [24] [  61/ 200] time: 773.1879, loss: 0.01533624
Epoch: [24] [  62/ 200] time: 773.3064, loss: 0.00351358
Epoch: [24] [  63/ 200] time: 773.4224, loss: 0.00210074
Epoch: [24] [  64/ 200] time: 773.5387, loss: 0.02821552
Epoch: [24] [  65/ 200] time: 773.6571, loss: 0.03812941
Epoch: [24] [  66/ 200] time: 773.7749, loss: 0.03867093
Epoch: [24] [  67/ 200] time: 773.8960, loss: 0.02152755
Epoch: [24] [  68/ 200] time: 774.0161, loss: 0.00728326
Epoch: [24] [  69/ 200] time: 7

Epoch: [24] [ 196/ 200] time: 789.0195, loss: 0.04143927
Epoch: [24] [ 197/ 200] time: 789.1386, loss: 0.01889027
Epoch: [24] [ 198/ 200] time: 789.2560, loss: 0.00421479
Epoch: [24] [ 199/ 200] time: 789.3750, loss: 0.00031363
[24/50] - ptime: 37.9501 loss: 0.01811726 acc: 0.96875 lr: 0.00077657
Epoch: [25] [   0/ 200] time: 802.0143, loss: 0.07187258
Epoch: [25] [   1/ 200] time: 802.1342, loss: 0.00059946
Epoch: [25] [   2/ 200] time: 802.2523, loss: 0.00851004
Epoch: [25] [   3/ 200] time: 802.3697, loss: 0.01684894
Epoch: [25] [   4/ 200] time: 802.4870, loss: 0.04105357
Epoch: [25] [   5/ 200] time: 802.6068, loss: 0.02935081
Epoch: [25] [   6/ 200] time: 802.7249, loss: 0.01625953
Epoch: [25] [   7/ 200] time: 802.8420, loss: 0.00723969
Epoch: [25] [   8/ 200] time: 802.9617, loss: 0.00314703
Epoch: [25] [   9/ 200] time: 803.0794, loss: 0.04051938
Epoch: [25] [  10/ 200] time: 803.1967, loss: 0.01723994
Epoch: [25] [  11/ 200] time: 803.3147, loss: 0.02045937
Epoch: [25] [  12/

Epoch: [25] [ 140/ 200] time: 818.5374, loss: 0.00772903
Epoch: [25] [ 141/ 200] time: 818.6573, loss: 0.20910957
Epoch: [25] [ 142/ 200] time: 818.7745, loss: 0.00274565
Epoch: [25] [ 143/ 200] time: 818.8921, loss: 0.02285146
Epoch: [25] [ 144/ 200] time: 819.0101, loss: 0.14110003
Epoch: [25] [ 145/ 200] time: 819.1276, loss: 0.01238259
Epoch: [25] [ 146/ 200] time: 819.2452, loss: 0.02610248
Epoch: [25] [ 147/ 200] time: 819.3640, loss: 0.03716727
Epoch: [25] [ 148/ 200] time: 819.4822, loss: 0.04955284
Epoch: [25] [ 149/ 200] time: 819.6022, loss: 0.00220159
Epoch: [25] [ 150/ 200] time: 819.7203, loss: 0.02679792
Epoch: [25] [ 151/ 200] time: 819.8385, loss: 0.03073796
Epoch: [25] [ 152/ 200] time: 819.9567, loss: 0.00039529
Epoch: [25] [ 153/ 200] time: 820.0751, loss: 0.07012379
Epoch: [25] [ 154/ 200] time: 820.1931, loss: 0.03596517
Epoch: [25] [ 155/ 200] time: 820.3107, loss: 0.00439783
Epoch: [25] [ 156/ 200] time: 820.4289, loss: 0.09026661
Epoch: [25] [ 157/ 200] time: 8

Epoch: [26] [  84/ 200] time: 837.4944, loss: 0.02428185
Epoch: [26] [  85/ 200] time: 837.6116, loss: 0.00897561
Epoch: [26] [  86/ 200] time: 837.7289, loss: 0.01726664
Epoch: [26] [  87/ 200] time: 837.8448, loss: 0.03611914
Epoch: [26] [  88/ 200] time: 837.9620, loss: 0.00549506
Epoch: [26] [  89/ 200] time: 838.0787, loss: 0.00266186
Epoch: [26] [  90/ 200] time: 838.1960, loss: 0.01779411
Epoch: [26] [  91/ 200] time: 838.3127, loss: 0.02228001
Epoch: [26] [  92/ 200] time: 838.4293, loss: 0.01051425
Epoch: [26] [  93/ 200] time: 838.5462, loss: 0.00054162
Epoch: [26] [  94/ 200] time: 838.6678, loss: 0.02312061
Epoch: [26] [  95/ 200] time: 838.7843, loss: 0.00091546
Epoch: [26] [  96/ 200] time: 838.9010, loss: 0.00088224
Epoch: [26] [  97/ 200] time: 839.0171, loss: 0.00296168
Epoch: [26] [  98/ 200] time: 839.1335, loss: 0.02701798
Epoch: [26] [  99/ 200] time: 839.2497, loss: 0.08077993
Epoch: [26] [ 100/ 200] time: 839.3652, loss: 0.00993251
Epoch: [26] [ 101/ 200] time: 8

Epoch: [27] [  28/ 200] time: 867.4058, loss: 0.00068676
Epoch: [27] [  29/ 200] time: 867.5224, loss: 0.00316910
Epoch: [27] [  30/ 200] time: 867.6404, loss: 0.00108435
Epoch: [27] [  31/ 200] time: 867.7568, loss: 0.01711858
Epoch: [27] [  32/ 200] time: 867.8739, loss: 0.00297434
Epoch: [27] [  33/ 200] time: 867.9900, loss: 0.01230300
Epoch: [27] [  34/ 200] time: 868.1084, loss: 0.00261199
Epoch: [27] [  35/ 200] time: 868.2248, loss: 0.00058526
Epoch: [27] [  36/ 200] time: 868.3417, loss: 0.00297414
Epoch: [27] [  37/ 200] time: 868.4579, loss: 0.01545364
Epoch: [27] [  38/ 200] time: 868.5748, loss: 0.00154224
Epoch: [27] [  39/ 200] time: 868.6939, loss: 0.00535036
Epoch: [27] [  40/ 200] time: 868.8111, loss: 0.00071556
Epoch: [27] [  41/ 200] time: 868.9275, loss: 0.00516838
Epoch: [27] [  42/ 200] time: 869.0447, loss: 0.03692208
Epoch: [27] [  43/ 200] time: 869.1619, loss: 0.00055843
Epoch: [27] [  44/ 200] time: 869.2790, loss: 0.00789070
Epoch: [27] [  45/ 200] time: 8

Epoch: [27] [ 172/ 200] time: 884.2363, loss: 0.08115254
Epoch: [27] [ 173/ 200] time: 884.3522, loss: 0.07103546
Epoch: [27] [ 174/ 200] time: 884.4686, loss: 0.00120461
Epoch: [27] [ 175/ 200] time: 884.5859, loss: 0.01086644
Epoch: [27] [ 176/ 200] time: 884.7035, loss: 0.02406978
Epoch: [27] [ 177/ 200] time: 884.8209, loss: 0.03801868
Epoch: [27] [ 178/ 200] time: 884.9377, loss: 0.00236136
Epoch: [27] [ 179/ 200] time: 885.0535, loss: 0.00379972
Epoch: [27] [ 180/ 200] time: 885.1716, loss: 0.01501497
Epoch: [27] [ 181/ 200] time: 885.2876, loss: 0.04961818
Epoch: [27] [ 182/ 200] time: 885.4042, loss: 0.13735311
Epoch: [27] [ 183/ 200] time: 885.5205, loss: 0.00486585
Epoch: [27] [ 184/ 200] time: 885.6391, loss: 0.02052651
Epoch: [27] [ 185/ 200] time: 885.7558, loss: 0.07657122
Epoch: [27] [ 186/ 200] time: 885.8724, loss: 0.07948770
Epoch: [27] [ 187/ 200] time: 885.9884, loss: 0.10902197
Epoch: [27] [ 188/ 200] time: 886.1052, loss: 0.00600192
Epoch: [27] [ 189/ 200] time: 8

Epoch: [28] [ 116/ 200] time: 916.5433, loss: 0.00061763
Epoch: [28] [ 117/ 200] time: 916.6610, loss: 0.00386032
Epoch: [28] [ 118/ 200] time: 916.7776, loss: 0.01854698
Epoch: [28] [ 119/ 200] time: 916.8961, loss: 0.00276965
Epoch: [28] [ 120/ 200] time: 917.0147, loss: 0.08138905
Epoch: [28] [ 121/ 200] time: 917.1319, loss: 0.00240690
Epoch: [28] [ 122/ 200] time: 917.2485, loss: 0.00498207
Epoch: [28] [ 123/ 200] time: 917.3645, loss: 0.00864219
Epoch: [28] [ 124/ 200] time: 917.4811, loss: 0.00276206
Epoch: [28] [ 125/ 200] time: 917.5984, loss: 0.00343882
Epoch: [28] [ 126/ 200] time: 917.7148, loss: 0.00293000
Epoch: [28] [ 127/ 200] time: 917.8310, loss: 0.00234945
Epoch: [28] [ 128/ 200] time: 917.9493, loss: 0.03523948
Epoch: [28] [ 129/ 200] time: 918.0653, loss: 0.01425998
Epoch: [28] [ 130/ 200] time: 918.1820, loss: 0.05866060
Epoch: [28] [ 131/ 200] time: 918.2984, loss: 0.04250991
Epoch: [28] [ 132/ 200] time: 918.4150, loss: 0.00637321
Epoch: [28] [ 133/ 200] time: 9

Epoch: [29] [  60/ 200] time: 949.2645, loss: 0.01284530
Epoch: [29] [  61/ 200] time: 949.3803, loss: 0.00139505
Epoch: [29] [  62/ 200] time: 949.4987, loss: 0.03261650
Epoch: [29] [  63/ 200] time: 949.6176, loss: 0.00191703
Epoch: [29] [  64/ 200] time: 949.7351, loss: 0.09640264
Epoch: [29] [  65/ 200] time: 949.8520, loss: 0.01056479
Epoch: [29] [  66/ 200] time: 949.9697, loss: 0.00300020
Epoch: [29] [  67/ 200] time: 950.0876, loss: 0.11503827
Epoch: [29] [  68/ 200] time: 950.2051, loss: 0.00418317
Epoch: [29] [  69/ 200] time: 950.3223, loss: 0.00837737
Epoch: [29] [  70/ 200] time: 950.4407, loss: 0.00249687
Epoch: [29] [  71/ 200] time: 950.5583, loss: 0.02500359
Epoch: [29] [  72/ 200] time: 950.6770, loss: 0.00229745
Epoch: [29] [  73/ 200] time: 950.7945, loss: 0.00524782
Epoch: [29] [  74/ 200] time: 950.9121, loss: 0.00953564
Epoch: [29] [  75/ 200] time: 951.0295, loss: 0.01182533
Epoch: [29] [  76/ 200] time: 951.1487, loss: 0.01019492
Epoch: [29] [  77/ 200] time: 9

Epoch: [30] [   4/ 200] time: 982.1075, loss: 0.00222440
Epoch: [30] [   5/ 200] time: 982.2240, loss: 0.00066383
Epoch: [30] [   6/ 200] time: 982.3415, loss: 0.00055979
Epoch: [30] [   7/ 200] time: 982.4586, loss: 0.00053230
Epoch: [30] [   8/ 200] time: 982.5760, loss: 0.00058727
Epoch: [30] [   9/ 200] time: 982.6926, loss: 0.00060063
Epoch: [30] [  10/ 200] time: 982.8097, loss: 0.00028309
Epoch: [30] [  11/ 200] time: 982.9255, loss: 0.00161669
Epoch: [30] [  12/ 200] time: 983.0421, loss: 0.00093794
Epoch: [30] [  13/ 200] time: 983.1588, loss: 0.00724997
Epoch: [30] [  14/ 200] time: 983.2758, loss: 0.00046526
Epoch: [30] [  15/ 200] time: 983.3934, loss: 0.00065514
Epoch: [30] [  16/ 200] time: 983.5105, loss: 0.02370843
Epoch: [30] [  17/ 200] time: 983.6282, loss: 0.00042226
Epoch: [30] [  18/ 200] time: 983.7449, loss: 0.00928574
Epoch: [30] [  19/ 200] time: 983.8619, loss: 0.00110402
Epoch: [30] [  20/ 200] time: 983.9797, loss: 0.00091877
Epoch: [30] [  21/ 200] time: 9

Epoch: [30] [ 148/ 200] time: 998.9923, loss: 0.00866525
Epoch: [30] [ 149/ 200] time: 999.1085, loss: 0.01196240
Epoch: [30] [ 150/ 200] time: 999.2256, loss: 0.01092266
Epoch: [30] [ 151/ 200] time: 999.3417, loss: 0.00654934
Epoch: [30] [ 152/ 200] time: 999.4588, loss: 0.05887482
Epoch: [30] [ 153/ 200] time: 999.5765, loss: 0.00688698
Epoch: [30] [ 154/ 200] time: 999.6941, loss: 0.00213015
Epoch: [30] [ 155/ 200] time: 999.8105, loss: 0.00407666
Epoch: [30] [ 156/ 200] time: 999.9276, loss: 0.01141790
Epoch: [30] [ 157/ 200] time: 1000.0449, loss: 0.00360020
Epoch: [30] [ 158/ 200] time: 1000.1632, loss: 0.00681056
Epoch: [30] [ 159/ 200] time: 1000.2805, loss: 0.00951669
Epoch: [30] [ 160/ 200] time: 1000.3979, loss: 0.00368402
Epoch: [30] [ 161/ 200] time: 1000.5150, loss: 0.00104887
Epoch: [30] [ 162/ 200] time: 1000.6337, loss: 0.00808308
Epoch: [30] [ 163/ 200] time: 1000.7509, loss: 0.00393931
Epoch: [30] [ 164/ 200] time: 1000.8684, loss: 0.00095016
Epoch: [30] [ 165/ 200]

Epoch: [31] [  90/ 200] time: 1029.1391, loss: 0.00663617
Epoch: [31] [  91/ 200] time: 1029.2550, loss: 0.01065049
Epoch: [31] [  92/ 200] time: 1029.3725, loss: 0.00846557
Epoch: [31] [  93/ 200] time: 1029.4890, loss: 0.00251329
Epoch: [31] [  94/ 200] time: 1029.6073, loss: 0.01722629
Epoch: [31] [  95/ 200] time: 1029.7242, loss: 0.00125047
Epoch: [31] [  96/ 200] time: 1029.8414, loss: 0.00136218
Epoch: [31] [  97/ 200] time: 1029.9581, loss: 0.02901973
Epoch: [31] [  98/ 200] time: 1030.0755, loss: 0.01183450
Epoch: [31] [  99/ 200] time: 1030.1923, loss: 0.02577158
Epoch: [31] [ 100/ 200] time: 1030.3088, loss: 0.00120795
Epoch: [31] [ 101/ 200] time: 1030.4257, loss: 0.00846132
Epoch: [31] [ 102/ 200] time: 1030.5429, loss: 0.00087255
Epoch: [31] [ 103/ 200] time: 1030.6619, loss: 0.03490162
Epoch: [31] [ 104/ 200] time: 1030.7790, loss: 0.00784174
Epoch: [31] [ 105/ 200] time: 1030.8946, loss: 0.00724348
Epoch: [31] [ 106/ 200] time: 1031.0117, loss: 0.01933661
Epoch: [31] [ 

Epoch: [32] [  32/ 200] time: 1060.7803, loss: 0.03712672
Epoch: [32] [  33/ 200] time: 1060.8964, loss: 0.00303478
Epoch: [32] [  34/ 200] time: 1061.0132, loss: 0.01301274
Epoch: [32] [  35/ 200] time: 1061.1315, loss: 0.00164693
Epoch: [32] [  36/ 200] time: 1061.2485, loss: 0.00211616
Epoch: [32] [  37/ 200] time: 1061.3646, loss: 0.03437592
Epoch: [32] [  38/ 200] time: 1061.4813, loss: 0.00451757
Epoch: [32] [  39/ 200] time: 1061.6003, loss: 0.01369400
Epoch: [32] [  40/ 200] time: 1061.7179, loss: 0.04911611
Epoch: [32] [  41/ 200] time: 1061.8342, loss: 0.00106717
Epoch: [32] [  42/ 200] time: 1061.9513, loss: 0.00300845
Epoch: [32] [  43/ 200] time: 1062.0675, loss: 0.01671950
Epoch: [32] [  44/ 200] time: 1062.1864, loss: 0.00492536
Epoch: [32] [  45/ 200] time: 1062.3051, loss: 0.00834763
Epoch: [32] [  46/ 200] time: 1062.4222, loss: 0.00909517
Epoch: [32] [  47/ 200] time: 1062.5395, loss: 0.04947392
Epoch: [32] [  48/ 200] time: 1062.6585, loss: 0.00148851
Epoch: [32] [ 

Epoch: [32] [ 174/ 200] time: 1077.3918, loss: 0.00155704
Epoch: [32] [ 175/ 200] time: 1077.5080, loss: 0.00163766
Epoch: [32] [ 176/ 200] time: 1077.6259, loss: 0.00089875
Epoch: [32] [ 177/ 200] time: 1077.7420, loss: 0.04340813
Epoch: [32] [ 178/ 200] time: 1077.8613, loss: 0.00123314
Epoch: [32] [ 179/ 200] time: 1077.9778, loss: 0.02726725
Epoch: [32] [ 180/ 200] time: 1078.0943, loss: 0.00065889
Epoch: [32] [ 181/ 200] time: 1078.2114, loss: 0.00114863
Epoch: [32] [ 182/ 200] time: 1078.3280, loss: 0.00011948
Epoch: [32] [ 183/ 200] time: 1078.4443, loss: 0.00224614
Epoch: [32] [ 184/ 200] time: 1078.5608, loss: 0.00037886
Epoch: [32] [ 185/ 200] time: 1078.6776, loss: 0.01303434
Epoch: [32] [ 186/ 200] time: 1078.7946, loss: 0.01374210
Epoch: [32] [ 187/ 200] time: 1078.9106, loss: 0.00215210
Epoch: [32] [ 188/ 200] time: 1079.0273, loss: 0.00532373
Epoch: [32] [ 189/ 200] time: 1079.1452, loss: 0.00294555
Epoch: [32] [ 190/ 200] time: 1079.2621, loss: 0.00168857
Epoch: [32] [ 

Epoch: [33] [ 116/ 200] time: 1107.6399, loss: 0.01527382
Epoch: [33] [ 117/ 200] time: 1107.7578, loss: 0.00923341
Epoch: [33] [ 118/ 200] time: 1107.8741, loss: 0.00055691
Epoch: [33] [ 119/ 200] time: 1107.9900, loss: 0.01424843
Epoch: [33] [ 120/ 200] time: 1108.1069, loss: 0.00981622
Epoch: [33] [ 121/ 200] time: 1108.2228, loss: 0.00894416
Epoch: [33] [ 122/ 200] time: 1108.3395, loss: 0.00234027
Epoch: [33] [ 123/ 200] time: 1108.4555, loss: 0.02007180
Epoch: [33] [ 124/ 200] time: 1108.5717, loss: 0.00578893
Epoch: [33] [ 125/ 200] time: 1108.6892, loss: 0.00037538
Epoch: [33] [ 126/ 200] time: 1108.8059, loss: 0.00082402
Epoch: [33] [ 127/ 200] time: 1108.9223, loss: 0.00046498
Epoch: [33] [ 128/ 200] time: 1109.0392, loss: 0.02274781
Epoch: [33] [ 129/ 200] time: 1109.1565, loss: 0.00023914
Epoch: [33] [ 130/ 200] time: 1109.2731, loss: 0.00597791
Epoch: [33] [ 131/ 200] time: 1109.3890, loss: 0.00596950
Epoch: [33] [ 132/ 200] time: 1109.5053, loss: 0.02810065
Epoch: [33] [ 

Epoch: [34] [  58/ 200] time: 1137.7699, loss: 0.00752612
Epoch: [34] [  59/ 200] time: 1137.8877, loss: 0.00008510
Epoch: [34] [  60/ 200] time: 1138.0046, loss: 0.03275975
Epoch: [34] [  61/ 200] time: 1138.1212, loss: 0.02476812
Epoch: [34] [  62/ 200] time: 1138.2380, loss: 0.00340842
Epoch: [34] [  63/ 200] time: 1138.3537, loss: 0.00033627
Epoch: [34] [  64/ 200] time: 1138.4701, loss: 0.00741097
Epoch: [34] [  65/ 200] time: 1138.5874, loss: 0.00206796
Epoch: [34] [  66/ 200] time: 1138.7039, loss: 0.03126489
Epoch: [34] [  67/ 200] time: 1138.8213, loss: 0.00256194
Epoch: [34] [  68/ 200] time: 1138.9406, loss: 0.00178522
Epoch: [34] [  69/ 200] time: 1139.0576, loss: 0.00525172
Epoch: [34] [  70/ 200] time: 1139.1741, loss: 0.00439346
Epoch: [34] [  71/ 200] time: 1139.2900, loss: 0.01033592
Epoch: [34] [  72/ 200] time: 1139.4064, loss: 0.00113243
Epoch: [34] [  73/ 200] time: 1139.5230, loss: 0.00289085
Epoch: [34] [  74/ 200] time: 1139.6413, loss: 0.00001665
Epoch: [34] [ 

Epoch: [35] [   0/ 200] time: 1169.0342, loss: 0.00217264
Epoch: [35] [   1/ 200] time: 1169.1491, loss: 0.00246325
Epoch: [35] [   2/ 200] time: 1169.2651, loss: 0.00146159
Epoch: [35] [   3/ 200] time: 1169.3810, loss: 0.01067237
Epoch: [35] [   4/ 200] time: 1169.4996, loss: 0.00005394
Epoch: [35] [   5/ 200] time: 1169.6165, loss: 0.00170558
Epoch: [35] [   6/ 200] time: 1169.7336, loss: 0.00233052
Epoch: [35] [   7/ 200] time: 1169.8506, loss: 0.00031228
Epoch: [35] [   8/ 200] time: 1169.9677, loss: 0.01697530
Epoch: [35] [   9/ 200] time: 1170.0841, loss: 0.00041477
Epoch: [35] [  10/ 200] time: 1170.2009, loss: 0.00020032
Epoch: [35] [  11/ 200] time: 1170.3171, loss: 0.00033579
Epoch: [35] [  12/ 200] time: 1170.4336, loss: 0.00093576
Epoch: [35] [  13/ 200] time: 1170.5514, loss: 0.00136781
Epoch: [35] [  14/ 200] time: 1170.6693, loss: 0.00059717
Epoch: [35] [  15/ 200] time: 1170.7856, loss: 0.00148754
Epoch: [35] [  16/ 200] time: 1170.9024, loss: 0.00028318
Epoch: [35] [ 

Epoch: [35] [ 142/ 200] time: 1185.6490, loss: 0.00466580
Epoch: [35] [ 143/ 200] time: 1185.7650, loss: 0.00741398
Epoch: [35] [ 144/ 200] time: 1185.8825, loss: 0.00700185
Epoch: [35] [ 145/ 200] time: 1185.9993, loss: 0.00126871
Epoch: [35] [ 146/ 200] time: 1186.1169, loss: 0.00127661
Epoch: [35] [ 147/ 200] time: 1186.2334, loss: 0.00075053
Epoch: [35] [ 148/ 200] time: 1186.3500, loss: 0.01253454
Epoch: [35] [ 149/ 200] time: 1186.4663, loss: 0.00106683
Epoch: [35] [ 150/ 200] time: 1186.5844, loss: 0.00110671
Epoch: [35] [ 151/ 200] time: 1186.7023, loss: 0.00208769
Epoch: [35] [ 152/ 200] time: 1186.8192, loss: 0.01098617
Epoch: [35] [ 153/ 200] time: 1186.9354, loss: 0.01531978
Epoch: [35] [ 154/ 200] time: 1187.0544, loss: 0.00716054
Epoch: [35] [ 155/ 200] time: 1187.1705, loss: 0.10576833
Epoch: [35] [ 156/ 200] time: 1187.2876, loss: 0.00078010
Epoch: [35] [ 157/ 200] time: 1187.4047, loss: 0.02386419
Epoch: [35] [ 158/ 200] time: 1187.5216, loss: 0.00612344
Epoch: [35] [ 

Epoch: [36] [  84/ 200] time: 1218.5811, loss: 0.00042820
Epoch: [36] [  85/ 200] time: 1218.6969, loss: 0.00216368
Epoch: [36] [  86/ 200] time: 1218.8130, loss: 0.00101458
Epoch: [36] [  87/ 200] time: 1218.9294, loss: 0.00409028
Epoch: [36] [  88/ 200] time: 1219.0458, loss: 0.00103969
Epoch: [36] [  89/ 200] time: 1219.1619, loss: 0.00002999
Epoch: [36] [  90/ 200] time: 1219.2790, loss: 0.00064792
Epoch: [36] [  91/ 200] time: 1219.3960, loss: 0.00661598
Epoch: [36] [  92/ 200] time: 1219.5125, loss: 0.00000711
Epoch: [36] [  93/ 200] time: 1219.6313, loss: 0.00064489
Epoch: [36] [  94/ 200] time: 1219.7485, loss: 0.00001155
Epoch: [36] [  95/ 200] time: 1219.8660, loss: 0.00002937
Epoch: [36] [  96/ 200] time: 1219.9824, loss: 0.00089627
Epoch: [36] [  97/ 200] time: 1220.0981, loss: 0.02097225
Epoch: [36] [  98/ 200] time: 1220.2145, loss: 0.00070929
Epoch: [36] [  99/ 200] time: 1220.3316, loss: 0.00045985
Epoch: [36] [ 100/ 200] time: 1220.4482, loss: 0.00033979
Epoch: [36] [ 

Epoch: [37] [  26/ 200] time: 1250.0094, loss: 0.00001004
Epoch: [37] [  27/ 200] time: 1250.1256, loss: 0.00108072
Epoch: [37] [  28/ 200] time: 1250.2423, loss: 0.00922738
Epoch: [37] [  29/ 200] time: 1250.3585, loss: 0.00020023
Epoch: [37] [  30/ 200] time: 1250.4761, loss: 0.00072495
Epoch: [37] [  31/ 200] time: 1250.5933, loss: 0.00039389
Epoch: [37] [  32/ 200] time: 1250.7106, loss: 0.00157188
Epoch: [37] [  33/ 200] time: 1250.8285, loss: 0.00003565
Epoch: [37] [  34/ 200] time: 1250.9453, loss: 0.00139223
Epoch: [37] [  35/ 200] time: 1251.0617, loss: 0.00367646
Epoch: [37] [  36/ 200] time: 1251.1786, loss: 0.00010874
Epoch: [37] [  37/ 200] time: 1251.2948, loss: 0.00044285
Epoch: [37] [  38/ 200] time: 1251.4115, loss: 0.00001286
Epoch: [37] [  39/ 200] time: 1251.5281, loss: 0.00679003
Epoch: [37] [  40/ 200] time: 1251.6466, loss: 0.00016268
Epoch: [37] [  41/ 200] time: 1251.7645, loss: 0.00179755
Epoch: [37] [  42/ 200] time: 1251.8829, loss: 0.00054621
Epoch: [37] [ 

Epoch: [37] [ 168/ 200] time: 1266.6020, loss: 0.00028567
Epoch: [37] [ 169/ 200] time: 1266.7181, loss: 0.00193048
Epoch: [37] [ 170/ 200] time: 1266.8373, loss: 0.00638319
Epoch: [37] [ 171/ 200] time: 1266.9537, loss: 0.00164012
Epoch: [37] [ 172/ 200] time: 1267.0701, loss: 0.00003730
Epoch: [37] [ 173/ 200] time: 1267.1861, loss: 0.00009424
Epoch: [37] [ 174/ 200] time: 1267.3026, loss: 0.00012953
Epoch: [37] [ 175/ 200] time: 1267.4189, loss: 0.00168187
Epoch: [37] [ 176/ 200] time: 1267.5352, loss: 0.00026303
Epoch: [37] [ 177/ 200] time: 1267.6528, loss: 0.00000582
Epoch: [37] [ 178/ 200] time: 1267.7706, loss: 0.00870078
Epoch: [37] [ 179/ 200] time: 1267.8881, loss: 0.00049097
Epoch: [37] [ 180/ 200] time: 1268.0044, loss: 0.00143344
Epoch: [37] [ 181/ 200] time: 1268.1217, loss: 0.00147886
Epoch: [37] [ 182/ 200] time: 1268.2382, loss: 0.00122580
Epoch: [37] [ 183/ 200] time: 1268.3545, loss: 0.00302592
Epoch: [37] [ 184/ 200] time: 1268.4719, loss: 0.00535134
Epoch: [37] [ 

Epoch: [38] [ 110/ 200] time: 1298.2006, loss: 0.00589897
Epoch: [38] [ 111/ 200] time: 1298.3169, loss: 0.00129108
Epoch: [38] [ 112/ 200] time: 1298.4344, loss: 0.00026547
Epoch: [38] [ 113/ 200] time: 1298.5507, loss: 0.00592004
Epoch: [38] [ 114/ 200] time: 1298.6683, loss: 0.00000095
Epoch: [38] [ 115/ 200] time: 1298.7841, loss: 0.00014190
Epoch: [38] [ 116/ 200] time: 1298.9018, loss: 0.00006360
Epoch: [38] [ 117/ 200] time: 1299.0179, loss: 0.00003491
Epoch: [38] [ 118/ 200] time: 1299.1349, loss: 0.00070404
Epoch: [38] [ 119/ 200] time: 1299.2517, loss: 0.00152827
Epoch: [38] [ 120/ 200] time: 1299.3683, loss: 0.00005956
Epoch: [38] [ 121/ 200] time: 1299.4890, loss: 0.00017421
Epoch: [38] [ 122/ 200] time: 1299.6067, loss: 0.00092034
Epoch: [38] [ 123/ 200] time: 1299.7228, loss: 0.00016712
Epoch: [38] [ 124/ 200] time: 1299.8395, loss: 0.00120567
Epoch: [38] [ 125/ 200] time: 1299.9556, loss: 0.00027481
Epoch: [38] [ 126/ 200] time: 1300.0721, loss: 0.00678546
Epoch: [38] [ 

Epoch: [39] [  52/ 200] time: 1317.9445, loss: 0.00040822
Epoch: [39] [  53/ 200] time: 1318.0620, loss: 0.00476820
Epoch: [39] [  54/ 200] time: 1318.1789, loss: 0.08806982
Epoch: [39] [  55/ 200] time: 1318.2958, loss: 0.01023490
Epoch: [39] [  56/ 200] time: 1318.4126, loss: 0.00238176
Epoch: [39] [  57/ 200] time: 1318.5286, loss: 0.00004031
Epoch: [39] [  58/ 200] time: 1318.6467, loss: 0.00079368
Epoch: [39] [  59/ 200] time: 1318.7624, loss: 0.00197646
Epoch: [39] [  60/ 200] time: 1318.8809, loss: 0.00262058
Epoch: [39] [  61/ 200] time: 1318.9971, loss: 0.01961322
Epoch: [39] [  62/ 200] time: 1319.1138, loss: 0.00009796
Epoch: [39] [  63/ 200] time: 1319.2299, loss: 0.01745683
Epoch: [39] [  64/ 200] time: 1319.3462, loss: 0.00010094
Epoch: [39] [  65/ 200] time: 1319.4624, loss: 0.00074008
Epoch: [39] [  66/ 200] time: 1319.5790, loss: 0.00285259
Epoch: [39] [  67/ 200] time: 1319.6950, loss: 0.01044165
Epoch: [39] [  68/ 200] time: 1319.8115, loss: 0.00020063
Epoch: [39] [ 

Epoch: [39] [ 194/ 200] time: 1334.5322, loss: 0.00074503
Epoch: [39] [ 195/ 200] time: 1334.6489, loss: 0.00545977
Epoch: [39] [ 196/ 200] time: 1334.7655, loss: 0.02445837
Epoch: [39] [ 197/ 200] time: 1334.8833, loss: 0.00016287
Epoch: [39] [ 198/ 200] time: 1334.9996, loss: 0.00333870
Epoch: [39] [ 199/ 200] time: 1335.1158, loss: 0.00144425
[39/50] - ptime: 26.1497 loss: 0.01167192 acc: 0.98125 lr: 0.00066305
Epoch: [40] [   0/ 200] time: 1340.1281, loss: 0.00432626
Epoch: [40] [   1/ 200] time: 1340.2438, loss: 0.05896888
Epoch: [40] [   2/ 200] time: 1340.3609, loss: 0.00163751
Epoch: [40] [   3/ 200] time: 1340.4761, loss: 0.00511985
Epoch: [40] [   4/ 200] time: 1340.5938, loss: 0.08902484
Epoch: [40] [   5/ 200] time: 1340.7101, loss: 0.01247972
Epoch: [40] [   6/ 200] time: 1340.8276, loss: 0.04052737
Epoch: [40] [   7/ 200] time: 1340.9446, loss: 0.00642013
Epoch: [40] [   8/ 200] time: 1341.0616, loss: 0.00152492
Epoch: [40] [   9/ 200] time: 1341.1785, loss: 0.05848780
Ep

Epoch: [40] [ 136/ 200] time: 1356.0291, loss: 0.08382633
Epoch: [40] [ 137/ 200] time: 1356.1473, loss: 0.00247475
Epoch: [40] [ 138/ 200] time: 1356.2642, loss: 0.01055899
Epoch: [40] [ 139/ 200] time: 1356.3803, loss: 0.00479460
Epoch: [40] [ 140/ 200] time: 1356.4968, loss: 0.00465293
Epoch: [40] [ 141/ 200] time: 1356.6142, loss: 0.07659037
Epoch: [40] [ 142/ 200] time: 1356.7315, loss: 0.01750325
Epoch: [40] [ 143/ 200] time: 1356.8478, loss: 0.00497141
Epoch: [40] [ 144/ 200] time: 1356.9646, loss: 0.00156668
Epoch: [40] [ 145/ 200] time: 1357.0812, loss: 0.01206655
Epoch: [40] [ 146/ 200] time: 1357.1989, loss: 0.04590060
Epoch: [40] [ 147/ 200] time: 1357.3148, loss: 0.01035767
Epoch: [40] [ 148/ 200] time: 1357.4313, loss: 0.00260365
Epoch: [40] [ 149/ 200] time: 1357.5477, loss: 0.01521149
Epoch: [40] [ 150/ 200] time: 1357.6654, loss: 0.02557142
Epoch: [40] [ 151/ 200] time: 1357.7815, loss: 0.01268343
Epoch: [40] [ 152/ 200] time: 1357.8980, loss: 0.01520918
Epoch: [40] [ 

Epoch: [41] [  78/ 200] time: 1387.4606, loss: 0.00557366
Epoch: [41] [  79/ 200] time: 1387.5775, loss: 0.00773911
Epoch: [41] [  80/ 200] time: 1387.6949, loss: 0.01953236
Epoch: [41] [  81/ 200] time: 1387.8125, loss: 0.00045540
Epoch: [41] [  82/ 200] time: 1387.9294, loss: 0.00366893
Epoch: [41] [  83/ 200] time: 1388.0453, loss: 0.00191960
Epoch: [41] [  84/ 200] time: 1388.1625, loss: 0.00181746
Epoch: [41] [  85/ 200] time: 1388.2785, loss: 0.00469544
Epoch: [41] [  86/ 200] time: 1388.3958, loss: 0.00045962
Epoch: [41] [  87/ 200] time: 1388.5124, loss: 0.00350444
Epoch: [41] [  88/ 200] time: 1388.6300, loss: 0.00571846
Epoch: [41] [  89/ 200] time: 1388.7466, loss: 0.00635769
Epoch: [41] [  90/ 200] time: 1388.8649, loss: 0.00580619
Epoch: [41] [  91/ 200] time: 1388.9809, loss: 0.02437566
Epoch: [41] [  92/ 200] time: 1389.0974, loss: 0.00271576
Epoch: [41] [  93/ 200] time: 1389.2135, loss: 0.00027769
Epoch: [41] [  94/ 200] time: 1389.3308, loss: 0.00213697
Epoch: [41] [ 

Epoch: [42] [  20/ 200] time: 1418.7672, loss: 0.00031905
Epoch: [42] [  21/ 200] time: 1418.8838, loss: 0.00042838
Epoch: [42] [  22/ 200] time: 1418.9999, loss: 0.00021359
Epoch: [42] [  23/ 200] time: 1419.1172, loss: 0.00002751
Epoch: [42] [  24/ 200] time: 1419.2339, loss: 0.00209886
Epoch: [42] [  25/ 200] time: 1419.3505, loss: 0.00223734
Epoch: [42] [  26/ 200] time: 1419.4668, loss: 0.00036902
Epoch: [42] [  27/ 200] time: 1419.5847, loss: 0.00015912
Epoch: [42] [  28/ 200] time: 1419.7012, loss: 0.01056901
Epoch: [42] [  29/ 200] time: 1419.8176, loss: 0.01400775
Epoch: [42] [  30/ 200] time: 1419.9341, loss: 0.00020861
Epoch: [42] [  31/ 200] time: 1420.0518, loss: 0.00155512
Epoch: [42] [  32/ 200] time: 1420.1705, loss: 0.00473169
Epoch: [42] [  33/ 200] time: 1420.2868, loss: 0.00169081
Epoch: [42] [  34/ 200] time: 1420.4034, loss: 0.00001420
Epoch: [42] [  35/ 200] time: 1420.5199, loss: 0.00006303
Epoch: [42] [  36/ 200] time: 1420.6381, loss: 0.00104585
Epoch: [42] [ 

Epoch: [42] [ 162/ 200] time: 1435.3891, loss: 0.00508348
Epoch: [42] [ 163/ 200] time: 1435.5130, loss: 0.00009264
Epoch: [42] [ 164/ 200] time: 1435.6316, loss: 0.00085995
Epoch: [42] [ 165/ 200] time: 1435.7478, loss: 0.00277416
Epoch: [42] [ 166/ 200] time: 1435.8646, loss: 0.01263874
Epoch: [42] [ 167/ 200] time: 1435.9808, loss: 0.07061366
Epoch: [42] [ 168/ 200] time: 1436.0984, loss: 0.00241690
Epoch: [42] [ 169/ 200] time: 1436.2150, loss: 0.08362234
Epoch: [42] [ 170/ 200] time: 1436.3315, loss: 0.00043402
Epoch: [42] [ 171/ 200] time: 1436.4477, loss: 0.00045696
Epoch: [42] [ 172/ 200] time: 1436.5654, loss: 0.00259053
Epoch: [42] [ 173/ 200] time: 1436.6816, loss: 0.06274986
Epoch: [42] [ 174/ 200] time: 1436.7990, loss: 0.00122719
Epoch: [42] [ 175/ 200] time: 1436.9148, loss: 0.00447706
Epoch: [42] [ 176/ 200] time: 1437.0324, loss: 0.00310349
Epoch: [42] [ 177/ 200] time: 1437.1500, loss: 0.00082651
Epoch: [42] [ 178/ 200] time: 1437.2664, loss: 0.00226627
Epoch: [42] [ 

Epoch: [43] [ 104/ 200] time: 1466.7184, loss: 0.08547745
Epoch: [43] [ 105/ 200] time: 1466.8350, loss: 0.02505636
Epoch: [43] [ 106/ 200] time: 1466.9514, loss: 0.00051074
Epoch: [43] [ 107/ 200] time: 1467.0672, loss: 0.00609855
Epoch: [43] [ 108/ 200] time: 1467.1841, loss: 0.11116301
Epoch: [43] [ 109/ 200] time: 1467.2998, loss: 0.00224650
Epoch: [43] [ 110/ 200] time: 1467.4181, loss: 0.00042452
Epoch: [43] [ 111/ 200] time: 1467.5342, loss: 0.00063486
Epoch: [43] [ 112/ 200] time: 1467.6520, loss: 0.00352958
Epoch: [43] [ 113/ 200] time: 1467.7677, loss: 0.00165537
Epoch: [43] [ 114/ 200] time: 1467.8842, loss: 0.00061985
Epoch: [43] [ 115/ 200] time: 1468.0001, loss: 0.00002819
Epoch: [43] [ 116/ 200] time: 1468.1165, loss: 0.00244207
Epoch: [43] [ 117/ 200] time: 1468.2328, loss: 0.00063103
Epoch: [43] [ 118/ 200] time: 1468.3493, loss: 0.00005968
Epoch: [43] [ 119/ 200] time: 1468.4679, loss: 0.00329560
Epoch: [43] [ 120/ 200] time: 1468.5847, loss: 0.00331986
Epoch: [43] [ 

Epoch: [44] [  45/ 200] time: 1499.1119, loss: 0.00078775
Epoch: [44] [  46/ 200] time: 1499.2285, loss: 0.00408290
Epoch: [44] [  47/ 200] time: 1499.3474, loss: 0.00129536
Epoch: [44] [  48/ 200] time: 1499.4641, loss: 0.00124779
Epoch: [44] [  49/ 200] time: 1499.5816, loss: 0.00175278
Epoch: [44] [  50/ 200] time: 1499.6982, loss: 0.00408299
Epoch: [44] [  51/ 200] time: 1499.8155, loss: 0.00005037
Epoch: [44] [  52/ 200] time: 1499.9352, loss: 0.00060501
Epoch: [44] [  53/ 200] time: 1500.0521, loss: 0.00798126
Epoch: [44] [  54/ 200] time: 1500.1887, loss: 0.00005556
Epoch: [44] [  55/ 200] time: 1500.3065, loss: 0.00028488
Epoch: [44] [  56/ 200] time: 1500.4224, loss: 0.00021544
Epoch: [44] [  57/ 200] time: 1500.5389, loss: 0.00039001
Epoch: [44] [  58/ 200] time: 1500.6570, loss: 0.00010696
Epoch: [44] [  59/ 200] time: 1500.7748, loss: 0.00159219
Epoch: [44] [  60/ 200] time: 1500.8922, loss: 0.00023874
Epoch: [44] [  61/ 200] time: 1501.0090, loss: 0.00017710
Epoch: [44] [ 

Epoch: [44] [ 187/ 200] time: 1515.7109, loss: 0.00035132
Epoch: [44] [ 188/ 200] time: 1515.8267, loss: 0.00016151
Epoch: [44] [ 189/ 200] time: 1515.9427, loss: 0.00000470
Epoch: [44] [ 190/ 200] time: 1516.0588, loss: 0.00090064
Epoch: [44] [ 191/ 200] time: 1516.1753, loss: 0.00689714
Epoch: [44] [ 192/ 200] time: 1516.2923, loss: 0.00038046
Epoch: [44] [ 193/ 200] time: 1516.4095, loss: 0.00007144
Epoch: [44] [ 194/ 200] time: 1516.5256, loss: 0.00052028
Epoch: [44] [ 195/ 200] time: 1516.6430, loss: 0.00015931
Epoch: [44] [ 196/ 200] time: 1516.7604, loss: 0.00103413
Epoch: [44] [ 197/ 200] time: 1516.8773, loss: 0.00130124
Epoch: [44] [ 198/ 200] time: 1516.9935, loss: 0.00000756
Epoch: [44] [ 199/ 200] time: 1517.1100, loss: 0.00119094
[44/50] - ptime: 38.7299 loss: 0.00160868 acc: 0.98125 lr: 0.00062902
Epoch: [45] [   0/ 200] time: 1532.0946, loss: 0.00076188
Epoch: [45] [   1/ 200] time: 1532.2136, loss: 0.00028202
Epoch: [45] [   2/ 200] time: 1532.3325, loss: 0.00002997
Ep

Epoch: [45] [ 128/ 200] time: 1547.0795, loss: 0.00058837
Epoch: [45] [ 129/ 200] time: 1547.1955, loss: 0.00005510
Epoch: [45] [ 130/ 200] time: 1547.3124, loss: 0.00110738
Epoch: [45] [ 131/ 200] time: 1547.4285, loss: 0.00006682
Epoch: [45] [ 132/ 200] time: 1547.5451, loss: 0.00028372
Epoch: [45] [ 133/ 200] time: 1547.6636, loss: 0.00011138
Epoch: [45] [ 134/ 200] time: 1547.7814, loss: 0.00005421
Epoch: [45] [ 135/ 200] time: 1547.8982, loss: 0.00000221
Epoch: [45] [ 136/ 200] time: 1548.0146, loss: 0.00010716
Epoch: [45] [ 137/ 200] time: 1548.1307, loss: 0.00001341
Epoch: [45] [ 138/ 200] time: 1548.2477, loss: 0.00002800
Epoch: [45] [ 139/ 200] time: 1548.3644, loss: 0.00006041
Epoch: [45] [ 140/ 200] time: 1548.4810, loss: 0.00002626
Epoch: [45] [ 141/ 200] time: 1548.5981, loss: 0.00016981
Epoch: [45] [ 142/ 200] time: 1548.7142, loss: 0.00000450
Epoch: [45] [ 143/ 200] time: 1548.8310, loss: 0.00735416
Epoch: [45] [ 144/ 200] time: 1548.9480, loss: 0.00000428
Epoch: [45] [ 

Epoch: [46] [  70/ 200] time: 1578.1091, loss: 0.00285665
Epoch: [46] [  71/ 200] time: 1578.2256, loss: 0.00432766
Epoch: [46] [  72/ 200] time: 1578.3438, loss: 0.00001178
Epoch: [46] [  73/ 200] time: 1578.4603, loss: 0.00329497
Epoch: [46] [  74/ 200] time: 1578.5770, loss: 0.00147360
Epoch: [46] [  75/ 200] time: 1578.6941, loss: 0.00054084
Epoch: [46] [  76/ 200] time: 1578.8114, loss: 0.00001245
Epoch: [46] [  77/ 200] time: 1578.9285, loss: 0.00014521
Epoch: [46] [  78/ 200] time: 1579.0460, loss: 0.00066613
Epoch: [46] [  79/ 200] time: 1579.1633, loss: 0.00275821
Epoch: [46] [  80/ 200] time: 1579.2807, loss: 0.00026095
Epoch: [46] [  81/ 200] time: 1579.3976, loss: 0.00032838
Epoch: [46] [  82/ 200] time: 1579.5150, loss: 0.00700094
Epoch: [46] [  83/ 200] time: 1579.6326, loss: 0.00002085
Epoch: [46] [  84/ 200] time: 1579.7506, loss: 0.00032478
Epoch: [46] [  85/ 200] time: 1579.8672, loss: 0.00185661
Epoch: [46] [  86/ 200] time: 1579.9850, loss: 0.00590533
Epoch: [46] [ 

Epoch: [47] [  12/ 200] time: 1607.5719, loss: 0.00005759
Epoch: [47] [  13/ 200] time: 1607.6889, loss: 0.00065229
Epoch: [47] [  14/ 200] time: 1607.8065, loss: 0.00003208
Epoch: [47] [  15/ 200] time: 1607.9246, loss: 0.00035568
Epoch: [47] [  16/ 200] time: 1608.0428, loss: 0.00014326
Epoch: [47] [  17/ 200] time: 1608.1611, loss: 0.00006432
Epoch: [47] [  18/ 200] time: 1608.2780, loss: 0.00031557
Epoch: [47] [  19/ 200] time: 1608.3961, loss: 0.00071676
Epoch: [47] [  20/ 200] time: 1608.5131, loss: 0.00016463
Epoch: [47] [  21/ 200] time: 1608.6324, loss: 0.00001888
Epoch: [47] [  22/ 200] time: 1608.7498, loss: 0.00004904
Epoch: [47] [  23/ 200] time: 1608.8671, loss: 0.00558071
Epoch: [47] [  24/ 200] time: 1608.9849, loss: 0.00000229
Epoch: [47] [  25/ 200] time: 1609.1027, loss: 0.00003642
Epoch: [47] [  26/ 200] time: 1609.2198, loss: 0.00850404
Epoch: [47] [  27/ 200] time: 1609.3377, loss: 0.00569086
Epoch: [47] [  28/ 200] time: 1609.4556, loss: 0.00073333
Epoch: [47] [ 

Epoch: [47] [ 154/ 200] time: 1624.2953, loss: 0.02063257
Epoch: [47] [ 155/ 200] time: 1624.4133, loss: 0.05067713
Epoch: [47] [ 156/ 200] time: 1624.5308, loss: 0.02076986
Epoch: [47] [ 157/ 200] time: 1624.6488, loss: 0.00666488
Epoch: [47] [ 158/ 200] time: 1624.7665, loss: 0.00068425
Epoch: [47] [ 159/ 200] time: 1624.8847, loss: 0.00361728
Epoch: [47] [ 160/ 200] time: 1625.0028, loss: 0.00104535
Epoch: [47] [ 161/ 200] time: 1625.1207, loss: 0.07235388
Epoch: [47] [ 162/ 200] time: 1625.2380, loss: 0.00484259
Epoch: [47] [ 163/ 200] time: 1625.3558, loss: 0.02029164
Epoch: [47] [ 164/ 200] time: 1625.4728, loss: 0.00256205
Epoch: [47] [ 165/ 200] time: 1625.5925, loss: 0.00075327
Epoch: [47] [ 166/ 200] time: 1625.7127, loss: 0.00081813
Epoch: [47] [ 167/ 200] time: 1625.8294, loss: 0.00011728
Epoch: [47] [ 168/ 200] time: 1625.9473, loss: 0.00553028
Epoch: [47] [ 169/ 200] time: 1626.0646, loss: 0.03135688
Epoch: [47] [ 170/ 200] time: 1626.1824, loss: 0.00574663
Epoch: [47] [ 

Epoch: [48] [  96/ 200] time: 1643.0331, loss: 0.00089702
Epoch: [48] [  97/ 200] time: 1643.1485, loss: 0.00484294
Epoch: [48] [  98/ 200] time: 1643.2648, loss: 0.00088910
Epoch: [48] [  99/ 200] time: 1643.3807, loss: 0.00408768
Epoch: [48] [ 100/ 200] time: 1643.4970, loss: 0.00498105
Epoch: [48] [ 101/ 200] time: 1643.6146, loss: 0.00528479
Epoch: [48] [ 102/ 200] time: 1643.7322, loss: 0.00675280
Epoch: [48] [ 103/ 200] time: 1643.8491, loss: 0.00254305
Epoch: [48] [ 104/ 200] time: 1643.9654, loss: 0.00068295
Epoch: [48] [ 105/ 200] time: 1644.0811, loss: 0.00025617
Epoch: [48] [ 106/ 200] time: 1644.1975, loss: 0.01601507
Epoch: [48] [ 107/ 200] time: 1644.3133, loss: 0.00026308
Epoch: [48] [ 108/ 200] time: 1644.4302, loss: 0.00158640
Epoch: [48] [ 109/ 200] time: 1644.5461, loss: 0.00883168
Epoch: [48] [ 110/ 200] time: 1644.6654, loss: 0.00057971
Epoch: [48] [ 111/ 200] time: 1644.7813, loss: 0.01174689
Epoch: [48] [ 112/ 200] time: 1644.8976, loss: 0.00129015
Epoch: [48] [ 

Epoch: [49] [  38/ 200] time: 1661.1272, loss: 0.00235349
Epoch: [49] [  39/ 200] time: 1661.2438, loss: 0.00067137
Epoch: [49] [  40/ 200] time: 1661.3601, loss: 0.00201205
Epoch: [49] [  41/ 200] time: 1661.4758, loss: 0.00810090
Epoch: [49] [  42/ 200] time: 1661.5928, loss: 0.00035603
Epoch: [49] [  43/ 200] time: 1661.7097, loss: 0.00018423
Epoch: [49] [  44/ 200] time: 1661.8261, loss: 0.00093447
Epoch: [49] [  45/ 200] time: 1661.9420, loss: 0.01190081
Epoch: [49] [  46/ 200] time: 1662.0585, loss: 0.00034759
Epoch: [49] [  47/ 200] time: 1662.1746, loss: 0.00086728
Epoch: [49] [  48/ 200] time: 1662.2908, loss: 0.00404032
Epoch: [49] [  49/ 200] time: 1662.4065, loss: 0.00107974
Epoch: [49] [  50/ 200] time: 1662.5227, loss: 0.00009173
Epoch: [49] [  51/ 200] time: 1662.6412, loss: 0.00465668
Epoch: [49] [  52/ 200] time: 1662.7591, loss: 0.00093087
Epoch: [49] [  53/ 200] time: 1662.8752, loss: 0.00296924
Epoch: [49] [  54/ 200] time: 1662.9917, loss: 0.01006980
Epoch: [49] [ 

Epoch: [49] [ 180/ 200] time: 1677.6896, loss: 0.00014369
Epoch: [49] [ 181/ 200] time: 1677.8055, loss: 0.01072495
Epoch: [49] [ 182/ 200] time: 1677.9219, loss: 0.00023164
Epoch: [49] [ 183/ 200] time: 1678.0376, loss: 0.00003051
Epoch: [49] [ 184/ 200] time: 1678.1539, loss: 0.04520094
Epoch: [49] [ 185/ 200] time: 1678.2696, loss: 0.00154163
Epoch: [49] [ 186/ 200] time: 1678.3859, loss: 0.02637233
Epoch: [49] [ 187/ 200] time: 1678.5015, loss: 0.00006445
Epoch: [49] [ 188/ 200] time: 1678.6190, loss: 0.00121244
Epoch: [49] [ 189/ 200] time: 1678.7359, loss: 0.00330348
Epoch: [49] [ 190/ 200] time: 1678.8524, loss: 0.00134691
Epoch: [49] [ 191/ 200] time: 1678.9681, loss: 0.01166479
Epoch: [49] [ 192/ 200] time: 1679.0844, loss: 0.00405334
Epoch: [49] [ 193/ 200] time: 1679.2001, loss: 0.00011736
Epoch: [49] [ 194/ 200] time: 1679.3163, loss: 0.00008905
Epoch: [49] [ 195/ 200] time: 1679.4321, loss: 0.00017298
Epoch: [49] [ 196/ 200] time: 1679.5486, loss: 0.00761048
Epoch: [49] [ 

Epoch: [50] [ 122/ 200] time: 1695.7997, loss: 0.00027483
Epoch: [50] [ 123/ 200] time: 1695.9156, loss: 0.00030455
Epoch: [50] [ 124/ 200] time: 1696.0317, loss: 0.00086828
Epoch: [50] [ 125/ 200] time: 1696.1475, loss: 0.00593610
Epoch: [50] [ 126/ 200] time: 1696.2641, loss: 0.00113614
Epoch: [50] [ 127/ 200] time: 1696.3797, loss: 0.02409008
Epoch: [50] [ 128/ 200] time: 1696.4960, loss: 0.00814418
Epoch: [50] [ 129/ 200] time: 1696.6128, loss: 0.00446646
Epoch: [50] [ 130/ 200] time: 1696.7301, loss: 0.00734575
Epoch: [50] [ 131/ 200] time: 1696.8457, loss: 0.00134038
Epoch: [50] [ 132/ 200] time: 1696.9617, loss: 0.00032072
Epoch: [50] [ 133/ 200] time: 1697.0777, loss: 0.00061450
Epoch: [50] [ 134/ 200] time: 1697.1938, loss: 0.00011168
Epoch: [50] [ 135/ 200] time: 1697.3094, loss: 0.00003045
Epoch: [50] [ 136/ 200] time: 1697.4258, loss: 0.00098095
Epoch: [50] [ 137/ 200] time: 1697.5416, loss: 0.02394200
Epoch: [50] [ 138/ 200] time: 1697.6598, loss: 0.00090240
Epoch: [50] [ 

In [6]:
import pygame

file='/home/huiqy/Music/CloudMusic/All_Time_Low.mp3' #文件名是完整路径名
pygame.mixer.init() #初始化音频
track = pygame.mixer.music.load(file)#载入音乐文件
pygame.mixer.music.play()#开始播放
time.sleep(60)#播放10秒
pygame.mixer.music.stop()#停止播放