In [1]:
from __future__ import print_function, division

import tensorflow as tf

print(tf.__version__)

import keras

import matplotlib.pyplot as plt

import sys

from sklearn import preprocessing

import time
from tqdm import tqdm

from imutils import paths
from numpy import *
import numpy as np

from matplotlib.colors import Normalize

import argparse
import imutils,sklearn
import os, cv2, re, random, shutil, imageio, pickle

%matplotlib inline  

1.3.0


/home/huiqy/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
def atoi(text):
    return int(text) if text.isdigit() else text

def natural_keys(text):
    return [ atoi(c) for c in re.split('(\d+)', text) ]

def load_flower_data():
    # grab the list of images that we'll be describing
    print("[INFO] handling images...")
    TRAIN_ORIGINAL_DIR = './subsample/'
    TEST_DIR = './test/'

    # use this for full dataset
    train_images = [TRAIN_ORIGINAL_DIR + i for i in os.listdir(TRAIN_ORIGINAL_DIR)]
    test_images = [TEST_DIR + i for i in os.listdir(TEST_DIR)]
    
    train_images.sort(key=natural_keys)
    test_images.sort(key=natural_keys)

    # initialize the features matrix and labels list
    trainImage = []
    trainLabels = []
    testImage = []
    testLabels = []

    # loop over the input images
    for (i, imagePath) in enumerate(train_images):
        # extract the class label
        # get the labels from the name of the images by extract the string before "_"
        label = imagePath.split(os.path.sep)[-1].split("_")[0]

        # read and resize image
        img = cv2.imread(imagePath)
        img = cv2.resize(img, (128,128))

        # add the messages we got to features and labels matricies
        trainImage.append(img)
        trainLabels.append(label)

        # show an update every 100 images until the last image
        if i > 0 and ((i + 1) % 1000 == 0 or i == len(train_images) - 1):
            print("[INFO] processed {}/{}".format(i + 1, len(train_images)))
            
      # loop over the input images
    for (i, imagePath) in enumerate(test_images):
        # extract the class label
        # our images were named as labels.image_number.format
        # get the labels from the name of the images by extract the string before "."
        label = imagePath.split(os.path.sep)[-1].split("_")[0]

        # extract CNN features in the image
        img = cv2.imread(imagePath)
        img = cv2.resize(img, (128,128))

        # add the messages we got to features and labels matricies
        testImage.append(img)
        testLabels.append(label)

        # show an update every 100 images until the last image
        if i > 0 and ((i + 1) % 1000 == 0 or i == len(test_images) - 1):
            print("[INFO] processed {}/{}".format(i + 1, len(test_images)))


    trainImage = np.array(trainImage,dtype = float32)
    trainLabels = np.array(trainLabels)
    testImage = np.array(testImage,dtype = float32)
    testLabels = np.array(testLabels)
    print (trainImage.shape)
    
    trainImage = trainImage.astype(np.float32) / 255
    testImage = testImage.astype(np.float32) / 255
    
    le = preprocessing.LabelEncoder()
    le.fit(trainLabels)
    list(le.classes_)
    trainLabels = le.transform(trainLabels) 
    testLabels = le.transform(testLabels) 
    
    return trainImage, trainLabels, testImage, testLabels

In [3]:
trainImage, trainLabels, testImage, testLabels = load_flower_data()

nb_classes = 4

# Convert class vectors to binary class matrices.
trainLabels = keras.utils.to_categorical(trainLabels, nb_classes)
print (trainLabels)
testLabels = keras.utils.to_categorical(testLabels, nb_classes)
print (testLabels)
print (testLabels.shape)

np.save('../trainImage.npy', trainImage)
np.save('../trainLabels.npy', trainLabels)
np.save('../testImage.npy', testImage)
np.save('../testLabels.npy', testLabels)

print("[INFO] trainImage matrix: {:.2f}MB".format(
    (trainImage.nbytes) / (1024 * 1000.0)))
print("[INFO] trainLabels matrix: {:.4f}MB".format(
    (trainLabels.nbytes) / (1024 * 1000.0)))
print("[INFO] testImage matrix: {:.2f}MB".format(
    (testImage.nbytes) / (1024 * 1000.0)))
print("[INFO] testLabels matrix: {:.4f}MB".format(
    (testLabels.nbytes) / (1024 * 1000.0)))


[INFO] handling images...
[INFO] processed 1000/8000
[INFO] processed 2000/8000
[INFO] processed 3000/8000
[INFO] processed 4000/8000
[INFO] processed 5000/8000
[INFO] processed 6000/8000
[INFO] processed 7000/8000
[INFO] processed 8000/8000
[INFO] processed 240/240
(8000, 128, 128, 3)
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 ...
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [1. 0. 0. 0.]
 [

In [4]:
class CNN(object):
    def __init__(self, sess, epoch, batch_size, dataset_name, checkpoint_dir, log_dir, trainhist_dir):
        self.sess = sess
        self.dataset_name = dataset_name
        self.checkpoint_dir = checkpoint_dir
        self.log_dir = log_dir
        self.trainhist_dir = trainhist_dir
        self.epoch = epoch
        self.batch_size = batch_size

        # parameters
        self.input_height = 128
        self.input_width = 128
        self.c_dim = 3  # color dimension
        self.nb_class = 4
        
        # number of convolutional filters to use  
        self.nb_CNN = [32, 64, 64, 64, 128]    
        # number of dense filters to use  
        self.nb_Dense = [128] 
        # size of pooling area for max pooling  
        self.pool_size = (2, 2)  
        # convolution kernel size  
        self.kernel_size = (3, 3)
        self.batch_normalization_control = True
        
        # train   
        self.global_step = tf.Variable(0, trainable=False)
        self.initial_lr = 0.001 #初始学习率
        self.decay_steps = 10
        self.decay_rate = 0.9
        self.lr = tf.train.exponential_decay( self.initial_lr,
                                     global_step=self.global_step,
                                     decay_steps=self.decay_steps,
                                     decay_rate=self.decay_rate)
        self.beta1 = 0.5
        #max model to keep saving
        self.max_to_keep = 300

        # name for checkpoint
        self.model_name = 'CNN_C%d_D%d_Kernel(%d,%d)_%d_lrdecay0.0001' % (len(self.nb_CNN), len(self.nb_Dense),
                                                          self.kernel_size[0], self.kernel_size[1], max(self.nb_CNN))    
        
        # test

        #load_flower_data
        self.train_x = np.load('../trainImage.npy')
        self.train_y= np.load('../trainLabels.npy')
        self.test_x = np.load('../testImage.npy')
        self.test_y= np.load('../testLabels.npy')
        
        print ("Training:",self.train_x.shape[0])
        
        #记录
        self.train_hist = {}
        self.train_hist['losses'] = []
        self.train_hist['accuracy'] = []
        self.train_hist['learning_rate'] = []
        self.train_hist['per_epoch_ptimes'] = []
        self.train_hist['total_ptime'] = []
        
        # get number of batches for a single epoch
        self.num_batches_train = len(self.train_x) // self.batch_size
        self.num_batches_test= len(self.test_x) // self.batch_size

    def cnn_model(self, x, keep_prob, is_training=True, reuse=False):
        with tf.variable_scope("cnn", reuse=reuse):
             
            #初始化参数
            W = tf.truncated_normal_initializer(mean=0.0, stddev=0.02)
            B = tf.constant_initializer(0.0)
        
            print("CNN:x",x.get_shape()) # 128, 128, 3 

            #输入,卷积核为3*3 输出维度为32
            net = tf.layers.conv2d(inputs = x,                 # 输入,
                                    filters = self.nb_CNN[0],      # 卷积核个数,
                                    kernel_size = self.kernel_size,          # 卷积核尺寸
                                    strides = (1, 1),
                                    padding = 'same',              # padding方法
                                    kernel_initializer = W,
                                    bias_initializer = B,
                                    kernel_regularizer = None,
                                    bias_regularizer = None,
                                    activity_regularizer = None,
                                    name = 'conv_1'               # 命名用于获取变量
                                    )
            print("CNN:",net.get_shape())

            if self.batch_normalization_control:
                net = tf.layers.batch_normalization(net, training=is_training)
            net = tf.nn.relu(net, name = 'relu_conv_1')
            net = tf.layers.max_pooling2d(inputs = net,
                                          pool_size = self.pool_size,
                                          strides = (2, 2),
                                          padding='same',
                                          name='pool_conv_' + str(1)
                                         )
            print("CNN:",net.get_shape())
            
            for i in range(2,len(self.nb_CNN)+1):
                net = tf.layers.conv2d(inputs = net,                 # 输入,
                                       filters = self.nb_CNN[i-1],      # 卷积核个数,
                                       kernel_size = self.kernel_size,          # 卷积核尺寸
                                       strides = (1, 1),
                                       padding = 'same',              # padding方法
                                       kernel_initializer = W,
                                       bias_initializer = B,
                                       kernel_regularizer = None,
                                       bias_regularizer = None,
                                       activity_regularizer = None,
                                       name = 'conv_'+ str(i)        # 命名用于获取变量
                                       )
                print("CNN:",net.get_shape())
                if self.batch_normalization_control:
                    net = tf.layers.batch_normalization(net, training=is_training)
                net = tf.nn.relu( net, name = 'relu_conv_' + str(i))
                net = tf.layers.max_pooling2d(inputs = net,
                                              pool_size = self.pool_size,
                                              strides = (2, 2),
                                              padding = 'same',
                                              name = 'pool_conv_' + str(i)
                                             )

                print("CNN:",net.get_shape())

            #flatten
            net = tf.reshape(net, [-1, int(net.get_shape()[1]*net.get_shape()[2]*net.get_shape()[3])],name='flatten')
            print("CNN:",net.get_shape())
            
            #dense layer
            for i in range(1,len(self.nb_Dense)+1):
                net = tf.layers.dense(inputs = net,
                                    units = self.nb_Dense[i-1],
                                    kernel_initializer = W,
                                    bias_initializer = B,
                                    kernel_regularizer=None,
                                    bias_regularizer=None,
                                    activity_regularizer=None,
                                    name = 'dense_' + str(i)
                                    )
#                 net = tf.layers.batch_normalization(net, training=is_training)
                net = tf.nn.relu( net, name = 'relu_dense_' + str(i))
                net = tf.layers.dropout(inputs = net,
                                        rate=keep_prob,
                                        noise_shape=None,
                                        seed=None,
                                        training = is_training,
                                        name= 'dropout_dense_' + str(i)
                                        )
            #output
            logit = tf.layers.dense(inputs = net,
                                    units = self.nb_class,
                                    kernel_initializer = W,
                                    bias_initializer = B,
                                    kernel_regularizer=None,
                                    bias_regularizer=None,
                                    activity_regularizer=None,
                                    name = 'dense_output'
                                    )
            out_logit = tf.nn.softmax(logit, name="softmax")
            print("CNN:out_logit",out_logit.get_shape())
            print("------------------------")    

            return out_logit, logit


    def build_model(self):

        """ Graph Input """
        # images
        self.x = tf.placeholder(tf.float32, shape=[self.batch_size,self.input_height, self.input_width, self.c_dim], 
                                name='x_image')

        self.y = tf.placeholder(tf.float32, shape=[self.batch_size, self.nb_class], name='y_label')
        
        self.keep_prob = tf.placeholder(tf.float32)
        
        self.add_global = self.global_step.assign_add(1)

        """ Loss Function """

        # output of cnn_model
        self.out_logit, self.logit = self.cnn_model(self.x, self.keep_prob, is_training=True, reuse=False)
        
        self.loss_cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=self.y,
                                                                                         logits =self.logit))
        
        """ Training """
        tf_vars = tf.trainable_variables()
        cnn_vars = [var for var in tf_vars if var.name.startswith('cnn')]

        # optimizers
        with tf.control_dependencies(tf.get_collection(tf.GraphKeys.UPDATE_OPS)):
            self.cnn_optim = tf.train.AdamOptimizer(self.lr, beta1=self.beta1).minimize(self.loss_cross_entropy,
                                                                                        var_list=cnn_vars)
            
        """" Testing """
        # for test
        # output of cnn_model
        self.out_logit_test, self.logit_test = self.cnn_model(self.x, self.keep_prob, is_training=False, reuse=True)
        self.correct_prediction = tf.equal(tf.argmax(self.logit_test, 1), tf.argmax(self.y, 1))
        self.predict = tf.argmax(self.logit_test, 1)
        self.accuracy = tf.reduce_mean(tf.cast(self.correct_prediction, tf.float32))

        """ Summary """
        self.loss_sum = tf.summary.scalar("loss", self.loss_cross_entropy)


    def train(self):

        # initialize all variables
        tf.global_variables_initializer().run()

        # saver to save model
        self.saver = tf.train.Saver(max_to_keep = self.max_to_keep)

        # summary writer
        self.writer = tf.summary.FileWriter(self.log_dir + '/' + self.model_name, self.sess.graph)

        # restore check-point if it exits
        could_load, checkpoint_epoch = self.load(self.checkpoint_dir)
        if could_load:
            start_epoch = (int)(checkpoint_epoch) + 1
            counter = 1
            f = open(self.trainhist_dir + '/' + self.model_name+'_train_hist.pkl', 'rb') 
            self.train_hist = pickle.load(f)
            f.close()
            print(" [*] Load SUCCESS")
            print(" [!] START_EPOCH is ", start_epoch)
        else:
            start_epoch = 1
            counter = 1
            print(" [!] Load failed...")

        # loop for epoch
        start_time = time.time()
        for epoch_loop in range(start_epoch, self.epoch + 1):

            CNN_losses = []
  
            epoch_start_time = time.time()
            shuffle_idxs = random.sample(range(0, self.train_x.shape[0]), self.train_x.shape[0])
            shuffled_set = self.train_x[shuffle_idxs]
            shuffled_label = self.train_y[shuffle_idxs]
    
            # get batch data
            for idx in range(self.num_batches_train):
                batch_x = shuffled_set[idx*self.batch_size:(idx+1)*self.batch_size]
#                 batch_x = np.array(seq.augment_images(np.array(batch_x,dtype = uint8)),dtype = float32)
                batch_y = shuffled_label[idx*self.batch_size:(idx+1)*self.batch_size].reshape(
                                        [self.batch_size, self.nb_class])
                

                # update D network
                _, summary_str, cnn_loss = self.sess.run([self.cnn_optim, self.loss_sum, self.loss_cross_entropy],
                                               feed_dict={self.x: batch_x,
                                                          self.y: batch_y,
                                                          self.keep_prob: 0.5}
                                                      )
                self.writer.add_summary(summary_str, counter)

                CNN_losses.append(cnn_loss)

                # display training status            
                counter += 1
                print("Epoch: [%2d] [%4d/%4d] time: %4.4f, loss: %.8f" % (epoch_loop, idx, 
                                                                                    self.num_batches_train, 
                                                                          time.time() - start_time, cnn_loss))

            # After an epoch
            # Evaluates accuracy on test set
            test_accuracy_list = []
            for idx_test in range(self.num_batches_test):
                rand_index = np.random.choice(len(self.train_x), size=batch_size)
                batch_x_test = self.test_x[idx_test*self.batch_size:(idx_test+1)*self.batch_size]
                batch_y_tes = self.test_y[idx_test*self.batch_size:(idx_test+1)*self.batch_size].reshape(
                                        [self.batch_size, self.nb_class])
                accuracy = self.sess.run([self.accuracy],feed_dict={self.x: batch_x_test, 
                                                                   self.y: batch_y_tes,
                                                                   self.keep_prob: 1.0})
                test_accuracy_list.append(accuracy)
            test_accuracy = np.sum(test_accuracy_list)/self.num_batches_test
            
            #update learning rate
            _, rate = sess.run([self.add_global, self.lr])
                
            epoch_end_time = time.time()
            per_epoch_ptime = epoch_end_time - epoch_start_time
            
            print('[%d/%d] - ptime: %.4f loss: %.8f acc: %.5f lr: %.8f'% (epoch_loop, self.epoch, per_epoch_ptime, 
                                                                    np.mean(CNN_losses), test_accuracy, rate))
            self.train_hist['losses'].append(np.mean(CNN_losses))
            self.train_hist['accuracy'].append(test_accuracy)
            self.train_hist['learning_rate'].append(rate)
            self.train_hist['per_epoch_ptimes'].append(per_epoch_ptime)
            
            # save model
            self.save(self.checkpoint_dir, epoch_loop)
            
            # save trainhist for train
            f = open(self.trainhist_dir + '/' + self.model_name + '_train_hist.pkl', 'wb') 
            pickle.dump(self.train_hist, f)
            f.close()
            self.show_train_hist(self.train_hist, save=True, path= self.trainhist_dir + '/' 
                                 + self.model_name + '_train_hist.png')

        end_time = time.time()
        total_ptime = end_time - start_time
        self.train_hist['total_ptime'].append(total_ptime)
        print('Avg per epoch ptime: %.2f, total %d epochs ptime: %.2f' % (np.mean(self.train_hist['per_epoch_ptimes']), 
                                                                          self.epoch, total_ptime))
        print(" [*] Training finished!")
    
        """test after train"""
        best_acc = max(self.train_hist['accuracy'])
        beat_epoch = self.train_hist['accuracy'].index(best_acc) + 1
        print (" [*] Best Epoch: ", beat_epoch, ", Accuracy: ", best_acc)
        path_model = self.checkpoint_dir + '/' + self.model_name + '/'+ self.model_name +'-'+ str(beat_epoch)

        """ restore epoch """
        new_saver = tf.train.import_meta_graph(path_model + '.meta' )
        new_saver.restore(self.sess,path_model)

        # Evaluates accuracy on test set
        test_accuracy_list = []
        for idx_test in range(self.num_batches_test):
            batch_x_test = self.test_x[idx_test*self.batch_size:(idx_test+1)*self.batch_size]
            batch_y_tes = self.test_y[idx_test*self.batch_size:(idx_test+1)*self.batch_size].reshape(
                                    [self.batch_size, self.nb_class])
            accuracy = self.sess.run([self.accuracy],feed_dict={self.x: batch_x_test, 
                                                               self.y: batch_y_tes,
                                                               self.keep_prob: 1.0})
            test_accuracy_list.append(accuracy)
        test_accuracy = np.sum(test_accuracy_list)/self.num_batches_test
        print(" [*] Finished testing Best Epoch:", beat_epoch, ", accuracy: ",test_accuracy, "!")
        
    def test(self, epoch):
        path_model = self.checkpoint_dir + '/' + self.model_name + '/'+ self.model_name +'-'+ str(epoch)

        """ restore epoch """
        new_saver = tf.train.import_meta_graph(path_model + '.meta' )
        new_saver.restore(self.sess,path_model)

        # Evaluates accuracy on test set
        test_accuracy_list = []
        for idx_test in range(self.num_batches_test):
            batch_x_test = self.test_x[idx_test*self.batch_size:(idx_test+1)*self.batch_size]
            batch_y_tes = self.test_y[idx_test*self.batch_size:(idx_test+1)*self.batch_size].reshape(
                                    [self.batch_size, self.nb_class])
            accuracy = self.sess.run([self.accuracy],feed_dict={self.x: batch_x_test, 
                                                               self.y: batch_y_tes,
                                                               self.keep_prob: 1.0})
            test_accuracy_list.append(accuracy)
        test_accuracy = np.sum(test_accuracy_list)/self.num_batches_test
        print(" [*] Finished testing Epoch:", epoch, ", accuracy: ",test_accuracy, "!")
        
    def show_all_variables(self):
        model_vars = tf.trainable_variables()
        tf.contrib.slim.model_analyzer.analyze_vars(model_vars, print_info=True) 

    def save(self, checkpoint_dir, step):
        checkpoint_dir = os.path.join(checkpoint_dir, self.model_name)

        if not os.path.exists(checkpoint_dir):
            os.makedirs(checkpoint_dir)

        self.saver.save(self.sess,os.path.join(checkpoint_dir, self.model_name), global_step=step)

    def load(self, checkpoint_dir):
        import re
        print(" [*] Reading checkpoints...")
        checkpoint_dir = os.path.join(checkpoint_dir, self.model_name)

        ckpt = tf.train.get_checkpoint_state(checkpoint_dir)
        if ckpt and ckpt.model_checkpoint_path:
            ckpt_name = os.path.basename(ckpt.model_checkpoint_path)
            self.saver.restore(self.sess, os.path.join(checkpoint_dir, ckpt_name))
            epoch = int(next(re.finditer("(\d+)(?!.*\d)",ckpt_name)).group(0))
            print(" [*] Success to read [{}], epoch [{}]".format(ckpt_name,epoch))
            return True, epoch
        else:
            print(" [*] Failed to find a checkpoint")
            return False, 0
        
    def show_train_hist(self, hist, show = False, save = False, path = 'Train_hist.png'):
        x = range(1, len(hist['losses'])+1)

        y1 = hist['losses']
        y2 = hist['accuracy']
        
        fig, ax1 = plt.subplots()
                            
        ax2 = ax1.twinx()  

        ax1.plot(x, y1, 'b')
        ax2.plot(x, y2, 'r')
                            
        ax1.set_xlabel('Epoch')
                            
        ax1.set_ylabel('CNN_loss')    
        ax2.set_ylabel('accuracy')
                          
        plt.grid(True)
        plt.tight_layout()

        if save:
            plt.savefig(path, dpi = 400)

        if show:
            plt.show()
        else:
            plt.close()
   

In [ ]:
gan_type = 'CNN'
dataset = '4_Flowers'
epoch = 50
batch_size = 80
checkpoint_dir = 'checkpoint'
log_dir = 'logs'
trainhist_dir = 'trainhist'

if not os.path.exists(checkpoint_dir):
        os.makedirs(checkpoint_dir)

# --log_dir
if not os.path.exists(log_dir):
    os.makedirs(log_dir)
    
# --trainhist_dir
if not os.path.exists(trainhist_dir):
    os.makedirs(trainhist_dir)

# open session
with tf.Session(config=tf.ConfigProto(allow_soft_placement=True)) as sess:
    
    # declare instance for GAN
    CNN = CNN(sess, epoch=epoch, batch_size=batch_size, dataset_name=dataset, checkpoint_dir=checkpoint_dir, 
                log_dir=log_dir, trainhist_dir=trainhist_dir)

    # build graph
    CNN.build_model()

    # show network architecture
    CNN.show_all_variables()

    # launch the graph in a session
    CNN.train()
    
    #CNN.test(epoch)
        
sess.close()
        

# lrdecay
# Avg per epoch ptime: 12.58, total 50 epochs ptime: 647.16
#  [*] Training finished!
#  [*] Best Epoch:  17 , Accuracy:  0.9541666507720947
# INFO:tensorflow:Restoring parameters from checkpoint/CNN_C5_D1_Kernel(3,3)_128_lrdecay0.0001/CNN_C5_D1_Kernel(3,3)_128_lrdecay0.0001-17
#  [*] Finished testing Best Epoch: 17 , accuracy:  0.9541666507720947 !

Training: 8000
CNN:x (80, 128, 128, 3)
CNN: (80, 128, 128, 32)
CNN: (80, 64, 64, 32)
CNN: (80, 64, 64, 64)
CNN: (80, 32, 32, 64)
CNN: (80, 32, 32, 64)
CNN: (80, 16, 16, 64)
CNN: (80, 16, 16, 64)
CNN: (80, 8, 8, 64)
CNN: (80, 8, 8, 128)
CNN: (80, 4, 4, 128)
CNN: (80, 2048)
CNN:out_logit (80, 4)
------------------------
CNN:x (80, 128, 128, 3)
CNN: (80, 128, 128, 32)
CNN: (80, 64, 64, 32)
CNN: (80, 64, 64, 64)
CNN: (80, 32, 32, 64)
CNN: (80, 32, 32, 64)
CNN: (80, 16, 16, 64)
CNN: (80, 16, 16, 64)
CNN: (80, 8, 8, 64)
CNN: (80, 8, 8, 128)
CNN: (80, 4, 4, 128)
CNN: (80, 2048)
CNN:out_logit (80, 4)
------------------------
---------
Variables: name (type shape) [size]
---------
cnn/conv_1/kernel:0 (float32_ref 3x3x3x32) [864, bytes: 3456]
cnn/conv_1/bias:0 (float32_ref 32) [32, bytes: 128]
cnn/batch_normalization/beta:0 (float32_ref 32) [32, bytes: 128]
cnn/batch_normalization/gamma:0 (float32_ref 32) [32, bytes: 128]
cnn/conv_2/kernel:0 (float32_ref 3x3x32x64) [18432, bytes: 73728]
cnn/conv

Epoch: [ 2] [   6/ 100] time: 14.9533, loss: 0.51194912
Epoch: [ 2] [   7/ 100] time: 15.0689, loss: 0.48113635
Epoch: [ 2] [   8/ 100] time: 15.1854, loss: 0.52173805
Epoch: [ 2] [   9/ 100] time: 15.3010, loss: 0.42552489
Epoch: [ 2] [  10/ 100] time: 15.4175, loss: 0.44586921
Epoch: [ 2] [  11/ 100] time: 15.5333, loss: 0.29458088
Epoch: [ 2] [  12/ 100] time: 15.6491, loss: 0.44293791
Epoch: [ 2] [  13/ 100] time: 15.7646, loss: 0.38150442
Epoch: [ 2] [  14/ 100] time: 15.8803, loss: 0.31562036
Epoch: [ 2] [  15/ 100] time: 15.9960, loss: 0.50863606
Epoch: [ 2] [  16/ 100] time: 16.1116, loss: 0.43607020
Epoch: [ 2] [  17/ 100] time: 16.2281, loss: 0.35626113
Epoch: [ 2] [  18/ 100] time: 16.3437, loss: 0.28144994
Epoch: [ 2] [  19/ 100] time: 16.4603, loss: 0.34983081
Epoch: [ 2] [  20/ 100] time: 16.5759, loss: 0.34399068
Epoch: [ 2] [  21/ 100] time: 16.6913, loss: 0.49747586
Epoch: [ 2] [  22/ 100] time: 16.8067, loss: 0.38260216
Epoch: [ 2] [  23/ 100] time: 16.9224, loss: 0.3

Epoch: [ 3] [  52/ 100] time: 32.9486, loss: 0.24217895
Epoch: [ 3] [  53/ 100] time: 33.0645, loss: 0.36824635
Epoch: [ 3] [  54/ 100] time: 33.1820, loss: 0.33276302
Epoch: [ 3] [  55/ 100] time: 33.2978, loss: 0.38985276
Epoch: [ 3] [  56/ 100] time: 33.4150, loss: 0.16712523
Epoch: [ 3] [  57/ 100] time: 33.5315, loss: 0.19295374
Epoch: [ 3] [  58/ 100] time: 33.6474, loss: 0.25461155
Epoch: [ 3] [  59/ 100] time: 33.7632, loss: 0.38311106
Epoch: [ 3] [  60/ 100] time: 33.8794, loss: 0.26622313
Epoch: [ 3] [  61/ 100] time: 33.9960, loss: 0.20752123
Epoch: [ 3] [  62/ 100] time: 34.1129, loss: 0.18123969
Epoch: [ 3] [  63/ 100] time: 34.2295, loss: 0.38729560
Epoch: [ 3] [  64/ 100] time: 34.3457, loss: 0.16751274
Epoch: [ 3] [  65/ 100] time: 34.4629, loss: 0.25078678
Epoch: [ 3] [  66/ 100] time: 34.5789, loss: 0.35803428
Epoch: [ 3] [  67/ 100] time: 34.6955, loss: 0.31511587
Epoch: [ 3] [  68/ 100] time: 34.8111, loss: 0.24415630
Epoch: [ 3] [  69/ 100] time: 34.9270, loss: 0.3

Epoch: [ 4] [  98/ 100] time: 51.2103, loss: 0.08322574
Epoch: [ 4] [  99/ 100] time: 51.3365, loss: 0.29746968
[4/50] - ptime: 12.5752 loss: 0.21314768 acc: 0.85833 lr: 0.00095873
Epoch: [ 5] [   0/ 100] time: 52.4924, loss: 0.10585015
Epoch: [ 5] [   1/ 100] time: 52.6072, loss: 0.14109929
Epoch: [ 5] [   2/ 100] time: 52.7241, loss: 0.11846907
Epoch: [ 5] [   3/ 100] time: 52.8405, loss: 0.16893771
Epoch: [ 5] [   4/ 100] time: 52.9560, loss: 0.25662589
Epoch: [ 5] [   5/ 100] time: 53.0736, loss: 0.23165971
Epoch: [ 5] [   6/ 100] time: 53.1900, loss: 0.06445827
Epoch: [ 5] [   7/ 100] time: 53.3071, loss: 0.17497481
Epoch: [ 5] [   8/ 100] time: 53.4237, loss: 0.17195028
Epoch: [ 5] [   9/ 100] time: 53.5403, loss: 0.08312681
Epoch: [ 5] [  10/ 100] time: 53.6588, loss: 0.13230200
Epoch: [ 5] [  11/ 100] time: 53.7799, loss: 0.10969331
Epoch: [ 5] [  12/ 100] time: 53.9039, loss: 0.20675923
Epoch: [ 5] [  13/ 100] time: 54.0286, loss: 0.19475472
Epoch: [ 5] [  14/ 100] time: 54.15

Epoch: [ 6] [  42/ 100] time: 70.3803, loss: 0.09742427
Epoch: [ 6] [  43/ 100] time: 70.4965, loss: 0.17221430
Epoch: [ 6] [  44/ 100] time: 70.6127, loss: 0.15791783
Epoch: [ 6] [  45/ 100] time: 70.7291, loss: 0.09147124
Epoch: [ 6] [  46/ 100] time: 70.8453, loss: 0.11143366
Epoch: [ 6] [  47/ 100] time: 70.9614, loss: 0.09943257
Epoch: [ 6] [  48/ 100] time: 71.0777, loss: 0.07357304
Epoch: [ 6] [  49/ 100] time: 71.1935, loss: 0.06216942
Epoch: [ 6] [  50/ 100] time: 71.3117, loss: 0.07997140
Epoch: [ 6] [  51/ 100] time: 71.4290, loss: 0.04248011
Epoch: [ 6] [  52/ 100] time: 71.5453, loss: 0.09462978
Epoch: [ 6] [  53/ 100] time: 71.6611, loss: 0.10961495
Epoch: [ 6] [  54/ 100] time: 71.7772, loss: 0.08123219
Epoch: [ 6] [  55/ 100] time: 71.8934, loss: 0.17929646
Epoch: [ 6] [  56/ 100] time: 72.0098, loss: 0.16116346
Epoch: [ 6] [  57/ 100] time: 72.1261, loss: 0.19093284
Epoch: [ 6] [  58/ 100] time: 72.2434, loss: 0.13677661
Epoch: [ 6] [  59/ 100] time: 72.3594, loss: 0.1

Epoch: [ 7] [  88/ 100] time: 88.4012, loss: 0.16188148
Epoch: [ 7] [  89/ 100] time: 88.5177, loss: 0.16407990
Epoch: [ 7] [  90/ 100] time: 88.6342, loss: 0.15375471
Epoch: [ 7] [  91/ 100] time: 88.7507, loss: 0.03499734
Epoch: [ 7] [  92/ 100] time: 88.8673, loss: 0.12583503
Epoch: [ 7] [  93/ 100] time: 88.9833, loss: 0.05483350
Epoch: [ 7] [  94/ 100] time: 89.0997, loss: 0.07964566
Epoch: [ 7] [  95/ 100] time: 89.2162, loss: 0.09434961
Epoch: [ 7] [  96/ 100] time: 89.3356, loss: 0.10390149
Epoch: [ 7] [  97/ 100] time: 89.4531, loss: 0.09180686
Epoch: [ 7] [  98/ 100] time: 89.5696, loss: 0.13642469
Epoch: [ 7] [  99/ 100] time: 89.6859, loss: 0.10285198
[7/50] - ptime: 12.3200 loss: 0.12048963 acc: 0.84167 lr: 0.00092890
Epoch: [ 8] [   0/ 100] time: 90.8017, loss: 0.06824456
Epoch: [ 8] [   1/ 100] time: 90.9162, loss: 0.06181546
Epoch: [ 8] [   2/ 100] time: 91.0324, loss: 0.10836859
Epoch: [ 8] [   3/ 100] time: 91.1489, loss: 0.14592865
Epoch: [ 8] [   4/ 100] time: 91.26

Epoch: [ 9] [  32/ 100] time: 107.2274, loss: 0.05187938
Epoch: [ 9] [  33/ 100] time: 107.3458, loss: 0.06198958
Epoch: [ 9] [  34/ 100] time: 107.4632, loss: 0.05470283
Epoch: [ 9] [  35/ 100] time: 107.5792, loss: 0.09770473
Epoch: [ 9] [  36/ 100] time: 107.6965, loss: 0.04083081
Epoch: [ 9] [  37/ 100] time: 107.8126, loss: 0.10100803
Epoch: [ 9] [  38/ 100] time: 107.9288, loss: 0.11609309
Epoch: [ 9] [  39/ 100] time: 108.0455, loss: 0.06893530
Epoch: [ 9] [  40/ 100] time: 108.1619, loss: 0.09314386
Epoch: [ 9] [  41/ 100] time: 108.2789, loss: 0.04258561
Epoch: [ 9] [  42/ 100] time: 108.3974, loss: 0.04630293
Epoch: [ 9] [  43/ 100] time: 108.5145, loss: 0.07573123
Epoch: [ 9] [  44/ 100] time: 108.6313, loss: 0.03900945
Epoch: [ 9] [  45/ 100] time: 108.7478, loss: 0.15457784
Epoch: [ 9] [  46/ 100] time: 108.8643, loss: 0.02781472
Epoch: [ 9] [  47/ 100] time: 108.9807, loss: 0.04281241
Epoch: [ 9] [  48/ 100] time: 109.0972, loss: 0.10911418
Epoch: [ 9] [  49/ 100] time: 1

Epoch: [10] [  76/ 100] time: 125.0623, loss: 0.03669583
Epoch: [10] [  77/ 100] time: 125.1791, loss: 0.04695137
Epoch: [10] [  78/ 100] time: 125.2954, loss: 0.05741064
Epoch: [10] [  79/ 100] time: 125.4128, loss: 0.08411147
Epoch: [10] [  80/ 100] time: 125.5294, loss: 0.07674509
Epoch: [10] [  81/ 100] time: 125.6461, loss: 0.07550946
Epoch: [10] [  82/ 100] time: 125.7627, loss: 0.05338134
Epoch: [10] [  83/ 100] time: 125.8789, loss: 0.05801426
Epoch: [10] [  84/ 100] time: 125.9952, loss: 0.06414385
Epoch: [10] [  85/ 100] time: 126.1117, loss: 0.04127218
Epoch: [10] [  86/ 100] time: 126.2284, loss: 0.04712764
Epoch: [10] [  87/ 100] time: 126.3465, loss: 0.11487924
Epoch: [10] [  88/ 100] time: 126.4641, loss: 0.07430397
Epoch: [10] [  89/ 100] time: 126.5807, loss: 0.05785231
Epoch: [10] [  90/ 100] time: 126.6969, loss: 0.04859594
Epoch: [10] [  91/ 100] time: 126.8134, loss: 0.05362580
Epoch: [10] [  92/ 100] time: 126.9298, loss: 0.04259820
Epoch: [10] [  93/ 100] time: 1

Epoch: [12] [  18/ 100] time: 143.6201, loss: 0.06085750
Epoch: [12] [  19/ 100] time: 143.7364, loss: 0.11631879
Epoch: [12] [  20/ 100] time: 143.8532, loss: 0.08171233
Epoch: [12] [  21/ 100] time: 143.9696, loss: 0.08243427
Epoch: [12] [  22/ 100] time: 144.0860, loss: 0.04640162
Epoch: [12] [  23/ 100] time: 144.2024, loss: 0.07919374
Epoch: [12] [  24/ 100] time: 144.3189, loss: 0.07004281
Epoch: [12] [  25/ 100] time: 144.4368, loss: 0.11437397
Epoch: [12] [  26/ 100] time: 144.5537, loss: 0.01915653
Epoch: [12] [  27/ 100] time: 144.6702, loss: 0.08570840
Epoch: [12] [  28/ 100] time: 144.7866, loss: 0.02146196
Epoch: [12] [  29/ 100] time: 144.9030, loss: 0.08305107
Epoch: [12] [  30/ 100] time: 145.0195, loss: 0.04044628
Epoch: [12] [  31/ 100] time: 145.1359, loss: 0.03629651
Epoch: [12] [  32/ 100] time: 145.2524, loss: 0.04067905
Epoch: [12] [  33/ 100] time: 145.3708, loss: 0.02113181
Epoch: [12] [  34/ 100] time: 145.4885, loss: 0.06492251
Epoch: [12] [  35/ 100] time: 1

Epoch: [13] [  62/ 100] time: 161.4199, loss: 0.02198271
Epoch: [13] [  63/ 100] time: 161.5361, loss: 0.02724608
Epoch: [13] [  64/ 100] time: 161.6527, loss: 0.02494673
Epoch: [13] [  65/ 100] time: 161.7690, loss: 0.01388182
Epoch: [13] [  66/ 100] time: 161.8855, loss: 0.06517652
Epoch: [13] [  67/ 100] time: 162.0017, loss: 0.01009455
Epoch: [13] [  68/ 100] time: 162.1184, loss: 0.15520357
Epoch: [13] [  69/ 100] time: 162.2346, loss: 0.14277253
Epoch: [13] [  70/ 100] time: 162.3509, loss: 0.01703048
Epoch: [13] [  71/ 100] time: 162.4686, loss: 0.07402931
Epoch: [13] [  72/ 100] time: 162.5851, loss: 0.12728691
Epoch: [13] [  73/ 100] time: 162.7013, loss: 0.11062337
Epoch: [13] [  74/ 100] time: 162.8178, loss: 0.02215021
Epoch: [13] [  75/ 100] time: 162.9345, loss: 0.01091462
Epoch: [13] [  76/ 100] time: 163.0510, loss: 0.04318870
Epoch: [13] [  77/ 100] time: 163.1677, loss: 0.05692555
Epoch: [13] [  78/ 100] time: 163.2846, loss: 0.04619079
Epoch: [13] [  79/ 100] time: 1

Epoch: [15] [   4/ 100] time: 180.0280, loss: 0.02903235
Epoch: [15] [   5/ 100] time: 180.1451, loss: 0.08683170
Epoch: [15] [   6/ 100] time: 180.2620, loss: 0.00286373
Epoch: [15] [   7/ 100] time: 180.3792, loss: 0.02190041
Epoch: [15] [   8/ 100] time: 180.4970, loss: 0.02302950
Epoch: [15] [   9/ 100] time: 180.6135, loss: 0.08903679
Epoch: [15] [  10/ 100] time: 180.7301, loss: 0.03756714
Epoch: [15] [  11/ 100] time: 180.8464, loss: 0.02918972
Epoch: [15] [  12/ 100] time: 180.9630, loss: 0.00999624
Epoch: [15] [  13/ 100] time: 181.0791, loss: 0.02534034
Epoch: [15] [  14/ 100] time: 181.1952, loss: 0.02539579
Epoch: [15] [  15/ 100] time: 181.3124, loss: 0.05238494
Epoch: [15] [  16/ 100] time: 181.4306, loss: 0.03600821
Epoch: [15] [  17/ 100] time: 181.5469, loss: 0.02842496
Epoch: [15] [  18/ 100] time: 181.6634, loss: 0.03031911
Epoch: [15] [  19/ 100] time: 181.7799, loss: 0.04274984
Epoch: [15] [  20/ 100] time: 181.8963, loss: 0.02039096
Epoch: [15] [  21/ 100] time: 1

Epoch: [16] [  48/ 100] time: 197.8236, loss: 0.05238685
Epoch: [16] [  49/ 100] time: 197.9399, loss: 0.01042101
Epoch: [16] [  50/ 100] time: 198.0561, loss: 0.15292162
Epoch: [16] [  51/ 100] time: 198.1721, loss: 0.01754094
Epoch: [16] [  52/ 100] time: 198.2889, loss: 0.02898807
Epoch: [16] [  53/ 100] time: 198.4060, loss: 0.04544251
Epoch: [16] [  54/ 100] time: 198.5244, loss: 0.02123824
Epoch: [16] [  55/ 100] time: 198.6407, loss: 0.02474749
Epoch: [16] [  56/ 100] time: 198.7569, loss: 0.04643048
Epoch: [16] [  57/ 100] time: 198.8732, loss: 0.04512160
Epoch: [16] [  58/ 100] time: 198.9898, loss: 0.03098207
Epoch: [16] [  59/ 100] time: 199.1059, loss: 0.05752680
Epoch: [16] [  60/ 100] time: 199.2224, loss: 0.10959984
Epoch: [16] [  61/ 100] time: 199.3384, loss: 0.02606733
Epoch: [16] [  62/ 100] time: 199.4572, loss: 0.01612401
Epoch: [16] [  63/ 100] time: 199.5732, loss: 0.04944878
Epoch: [16] [  64/ 100] time: 199.6896, loss: 0.00858725
Epoch: [16] [  65/ 100] time: 1

Epoch: [17] [  92/ 100] time: 215.6131, loss: 0.00309895
Epoch: [17] [  93/ 100] time: 215.7294, loss: 0.00954610
Epoch: [17] [  94/ 100] time: 215.8460, loss: 0.05841650
Epoch: [17] [  95/ 100] time: 215.9631, loss: 0.01589340
Epoch: [17] [  96/ 100] time: 216.0798, loss: 0.01259454
Epoch: [17] [  97/ 100] time: 216.1958, loss: 0.03170583
Epoch: [17] [  98/ 100] time: 216.3126, loss: 0.00386325
Epoch: [17] [  99/ 100] time: 216.4299, loss: 0.15588598
[17/50] - ptime: 12.3173 loss: 0.03128843 acc: 0.95417 lr: 0.00083601
Epoch: [18] [   0/ 100] time: 217.5725, loss: 0.02069414
Epoch: [18] [   1/ 100] time: 217.6872, loss: 0.02089406
Epoch: [18] [   2/ 100] time: 217.8038, loss: 0.02394302
Epoch: [18] [   3/ 100] time: 217.9202, loss: 0.00577947
Epoch: [18] [   4/ 100] time: 218.0365, loss: 0.00507686
Epoch: [18] [   5/ 100] time: 218.1526, loss: 0.00565323
Epoch: [18] [   6/ 100] time: 218.2691, loss: 0.03147747
Epoch: [18] [   7/ 100] time: 218.3869, loss: 0.00959790
Epoch: [18] [   8/

Epoch: [19] [  34/ 100] time: 234.3397, loss: 0.01734697
Epoch: [19] [  35/ 100] time: 234.4571, loss: 0.04952995
Epoch: [19] [  36/ 100] time: 234.5753, loss: 0.00717299
Epoch: [19] [  37/ 100] time: 234.6917, loss: 0.04949094
Epoch: [19] [  38/ 100] time: 234.8083, loss: 0.07073535
Epoch: [19] [  39/ 100] time: 234.9245, loss: 0.01843314
Epoch: [19] [  40/ 100] time: 235.0416, loss: 0.01652184
Epoch: [19] [  41/ 100] time: 235.1574, loss: 0.01444747
Epoch: [19] [  42/ 100] time: 235.2738, loss: 0.01737251
Epoch: [19] [  43/ 100] time: 235.3909, loss: 0.00234741
Epoch: [19] [  44/ 100] time: 235.5079, loss: 0.01411348
Epoch: [19] [  45/ 100] time: 235.6240, loss: 0.00769295
Epoch: [19] [  46/ 100] time: 235.7416, loss: 0.02826294
Epoch: [19] [  47/ 100] time: 235.8588, loss: 0.04914454
Epoch: [19] [  48/ 100] time: 235.9749, loss: 0.00332975
Epoch: [19] [  49/ 100] time: 236.0999, loss: 0.00269335
Epoch: [19] [  50/ 100] time: 236.2174, loss: 0.00177762
Epoch: [19] [  51/ 100] time: 2

Epoch: [20] [  78/ 100] time: 252.1506, loss: 0.01163977
Epoch: [20] [  79/ 100] time: 252.2668, loss: 0.00334989
Epoch: [20] [  80/ 100] time: 252.3839, loss: 0.02270454
Epoch: [20] [  81/ 100] time: 252.5005, loss: 0.02200057
Epoch: [20] [  82/ 100] time: 252.6186, loss: 0.00499896
Epoch: [20] [  83/ 100] time: 252.7352, loss: 0.00477838
Epoch: [20] [  84/ 100] time: 252.8514, loss: 0.00180683
Epoch: [20] [  85/ 100] time: 252.9676, loss: 0.02142032
Epoch: [20] [  86/ 100] time: 253.0839, loss: 0.00621816
Epoch: [20] [  87/ 100] time: 253.2052, loss: 0.00317074
Epoch: [20] [  88/ 100] time: 253.3220, loss: 0.00651651
Epoch: [20] [  89/ 100] time: 253.4398, loss: 0.01600032
Epoch: [20] [  90/ 100] time: 253.5580, loss: 0.01684979
Epoch: [20] [  91/ 100] time: 253.6743, loss: 0.00733993
Epoch: [20] [  92/ 100] time: 253.7911, loss: 0.00622365
Epoch: [20] [  93/ 100] time: 253.9075, loss: 0.00155697
Epoch: [20] [  94/ 100] time: 254.0246, loss: 0.01504085
Epoch: [20] [  95/ 100] time: 2

Epoch: [22] [  20/ 100] time: 270.7512, loss: 0.00366755
Epoch: [22] [  21/ 100] time: 270.8678, loss: 0.02582443
Epoch: [22] [  22/ 100] time: 270.9842, loss: 0.00762463
Epoch: [22] [  23/ 100] time: 271.1007, loss: 0.00277872
Epoch: [22] [  24/ 100] time: 271.2171, loss: 0.01226170
Epoch: [22] [  25/ 100] time: 271.3332, loss: 0.02292460
Epoch: [22] [  26/ 100] time: 271.4508, loss: 0.00295398
Epoch: [22] [  27/ 100] time: 271.5682, loss: 0.00092797
Epoch: [22] [  28/ 100] time: 271.6858, loss: 0.00385752
Epoch: [22] [  29/ 100] time: 271.8018, loss: 0.00265665
Epoch: [22] [  30/ 100] time: 271.9182, loss: 0.01621695
Epoch: [22] [  31/ 100] time: 272.0342, loss: 0.02004434
Epoch: [22] [  32/ 100] time: 272.1504, loss: 0.00638579
Epoch: [22] [  33/ 100] time: 272.2668, loss: 0.00522073
Epoch: [22] [  34/ 100] time: 272.3835, loss: 0.00774845
Epoch: [22] [  35/ 100] time: 272.5003, loss: 0.01926375
Epoch: [22] [  36/ 100] time: 272.6183, loss: 0.01837032
Epoch: [22] [  37/ 100] time: 2

Epoch: [23] [  64/ 100] time: 288.6253, loss: 0.00387537
Epoch: [23] [  65/ 100] time: 288.7415, loss: 0.01674347
Epoch: [23] [  66/ 100] time: 288.8583, loss: 0.02879262
Epoch: [23] [  67/ 100] time: 288.9743, loss: 0.01677039
Epoch: [23] [  68/ 100] time: 289.0923, loss: 0.00540306
Epoch: [23] [  69/ 100] time: 289.2085, loss: 0.01786104
Epoch: [23] [  70/ 100] time: 289.3249, loss: 0.01870892
Epoch: [23] [  71/ 100] time: 289.4422, loss: 0.01949736
Epoch: [23] [  72/ 100] time: 289.5590, loss: 0.00428885
Epoch: [23] [  73/ 100] time: 289.6760, loss: 0.00285595
Epoch: [23] [  74/ 100] time: 289.7926, loss: 0.00862753
Epoch: [23] [  75/ 100] time: 289.9088, loss: 0.07099028
Epoch: [23] [  76/ 100] time: 290.0254, loss: 0.00226902
Epoch: [23] [  77/ 100] time: 290.1418, loss: 0.01536400
Epoch: [23] [  78/ 100] time: 290.2582, loss: 0.01274469
Epoch: [23] [  79/ 100] time: 290.3751, loss: 0.00513541
Epoch: [23] [  80/ 100] time: 290.4921, loss: 0.01815489
Epoch: [23] [  81/ 100] time: 2

Epoch: [25] [   6/ 100] time: 307.1691, loss: 0.01433840
Epoch: [25] [   7/ 100] time: 307.2855, loss: 0.01462303
Epoch: [25] [   8/ 100] time: 307.4026, loss: 0.01585093
Epoch: [25] [   9/ 100] time: 307.5188, loss: 0.00297296
Epoch: [25] [  10/ 100] time: 307.6363, loss: 0.00128306
Epoch: [25] [  11/ 100] time: 307.7522, loss: 0.00191664
Epoch: [25] [  12/ 100] time: 307.8689, loss: 0.01486793
Epoch: [25] [  13/ 100] time: 307.9848, loss: 0.00202711
Epoch: [25] [  14/ 100] time: 308.1017, loss: 0.00079266
Epoch: [25] [  15/ 100] time: 308.2179, loss: 0.00838101
Epoch: [25] [  16/ 100] time: 308.3345, loss: 0.00828359
Epoch: [25] [  17/ 100] time: 308.4522, loss: 0.01500851
Epoch: [25] [  18/ 100] time: 308.5689, loss: 0.00326267
Epoch: [25] [  19/ 100] time: 308.6858, loss: 0.01786190
Epoch: [25] [  20/ 100] time: 308.8022, loss: 0.00038118
Epoch: [25] [  21/ 100] time: 308.9186, loss: 0.00222773
Epoch: [25] [  22/ 100] time: 309.0352, loss: 0.03789226
Epoch: [25] [  23/ 100] time: 3

Epoch: [26] [  50/ 100] time: 324.9721, loss: 0.05360038
Epoch: [26] [  51/ 100] time: 325.0883, loss: 0.00401807
Epoch: [26] [  52/ 100] time: 325.2046, loss: 0.00568489
Epoch: [26] [  53/ 100] time: 325.3210, loss: 0.00033368
Epoch: [26] [  54/ 100] time: 325.4383, loss: 0.02700246
Epoch: [26] [  55/ 100] time: 325.5547, loss: 0.00384740
Epoch: [26] [  56/ 100] time: 325.6715, loss: 0.01788295
Epoch: [26] [  57/ 100] time: 325.7877, loss: 0.00170088
Epoch: [26] [  58/ 100] time: 325.9040, loss: 0.00208511
Epoch: [26] [  59/ 100] time: 326.0204, loss: 0.00122206
Epoch: [26] [  60/ 100] time: 326.1369, loss: 0.01404573
Epoch: [26] [  61/ 100] time: 326.2532, loss: 0.00314689
Epoch: [26] [  62/ 100] time: 326.3696, loss: 0.02396898
Epoch: [26] [  63/ 100] time: 326.4867, loss: 0.00435370
Epoch: [26] [  64/ 100] time: 326.6030, loss: 0.00478359
Epoch: [26] [  65/ 100] time: 326.7195, loss: 0.00784879
Epoch: [26] [  66/ 100] time: 326.8360, loss: 0.00618409
Epoch: [26] [  67/ 100] time: 3

Epoch: [27] [  94/ 100] time: 342.8128, loss: 0.01391994
Epoch: [27] [  95/ 100] time: 342.9290, loss: 0.00574272
Epoch: [27] [  96/ 100] time: 343.0455, loss: 0.03942787
Epoch: [27] [  97/ 100] time: 343.1615, loss: 0.04053742
Epoch: [27] [  98/ 100] time: 343.2784, loss: 0.02686237
Epoch: [27] [  99/ 100] time: 343.3959, loss: 0.03146575
[27/50] - ptime: 12.3282 loss: 0.02978933 acc: 0.95417 lr: 0.00075241
Epoch: [28] [   0/ 100] time: 344.5359, loss: 0.02156508
Epoch: [28] [   1/ 100] time: 344.6504, loss: 0.02069276
Epoch: [28] [   2/ 100] time: 344.7691, loss: 0.00985747
Epoch: [28] [   3/ 100] time: 344.8856, loss: 0.00494765
Epoch: [28] [   4/ 100] time: 345.0021, loss: 0.01042578
Epoch: [28] [   5/ 100] time: 345.1184, loss: 0.00434248
Epoch: [28] [   6/ 100] time: 345.2349, loss: 0.03877911
Epoch: [28] [   7/ 100] time: 345.3511, loss: 0.00477232
Epoch: [28] [   8/ 100] time: 345.4690, loss: 0.01615327
Epoch: [28] [   9/ 100] time: 345.5856, loss: 0.01544989
Epoch: [28] [  10/

Epoch: [29] [  36/ 100] time: 361.4291, loss: 0.00600030
Epoch: [29] [  37/ 100] time: 361.5450, loss: 0.00747616
Epoch: [29] [  38/ 100] time: 361.6616, loss: 0.00968448
Epoch: [29] [  39/ 100] time: 361.7780, loss: 0.00432176
Epoch: [29] [  40/ 100] time: 361.8945, loss: 0.00389067
Epoch: [29] [  41/ 100] time: 362.0107, loss: 0.01583127
Epoch: [29] [  42/ 100] time: 362.1272, loss: 0.03148170
Epoch: [29] [  43/ 100] time: 362.2435, loss: 0.00762493
Epoch: [29] [  44/ 100] time: 362.3600, loss: 0.00921354
Epoch: [29] [  45/ 100] time: 362.4771, loss: 0.00856435
Epoch: [29] [  46/ 100] time: 362.5943, loss: 0.05396198
Epoch: [29] [  47/ 100] time: 362.7112, loss: 0.00549300
Epoch: [29] [  48/ 100] time: 362.8289, loss: 0.00058136
Epoch: [29] [  49/ 100] time: 362.9450, loss: 0.00510825
Epoch: [29] [  50/ 100] time: 363.0612, loss: 0.00387382
Epoch: [29] [  51/ 100] time: 363.1778, loss: 0.02137709
Epoch: [29] [  52/ 100] time: 363.2945, loss: 0.00920269
Epoch: [29] [  53/ 100] time: 3

Epoch: [30] [  80/ 100] time: 379.2216, loss: 0.07275358
Epoch: [30] [  81/ 100] time: 379.3377, loss: 0.02246366
Epoch: [30] [  82/ 100] time: 379.4555, loss: 0.01191099
Epoch: [30] [  83/ 100] time: 379.5722, loss: 0.02413948
Epoch: [30] [  84/ 100] time: 379.6887, loss: 0.00665769
Epoch: [30] [  85/ 100] time: 379.8059, loss: 0.00292355
Epoch: [30] [  86/ 100] time: 379.9225, loss: 0.00225723
Epoch: [30] [  87/ 100] time: 380.0395, loss: 0.01070926
Epoch: [30] [  88/ 100] time: 380.1564, loss: 0.01828230
Epoch: [30] [  89/ 100] time: 380.2732, loss: 0.04996757
Epoch: [30] [  90/ 100] time: 380.3903, loss: 0.01189388
Epoch: [30] [  91/ 100] time: 380.5066, loss: 0.00074506
Epoch: [30] [  92/ 100] time: 380.6230, loss: 0.04018742
Epoch: [30] [  93/ 100] time: 380.7406, loss: 0.00189494
Epoch: [30] [  94/ 100] time: 380.8594, loss: 0.01282036
Epoch: [30] [  95/ 100] time: 380.9761, loss: 0.00600239
Epoch: [30] [  96/ 100] time: 381.0927, loss: 0.02989139
Epoch: [30] [  97/ 100] time: 3

Epoch: [32] [  22/ 100] time: 397.8737, loss: 0.00258181
Epoch: [32] [  23/ 100] time: 397.9906, loss: 0.00618559
Epoch: [32] [  24/ 100] time: 398.1068, loss: 0.00234922
Epoch: [32] [  25/ 100] time: 398.2248, loss: 0.02165456
Epoch: [32] [  26/ 100] time: 398.3415, loss: 0.01556836
Epoch: [32] [  27/ 100] time: 398.4643, loss: 0.00418912
Epoch: [32] [  28/ 100] time: 398.5863, loss: 0.03816298
Epoch: [32] [  29/ 100] time: 398.7117, loss: 0.00073206
Epoch: [32] [  30/ 100] time: 398.8371, loss: 0.00205484
Epoch: [32] [  31/ 100] time: 398.9621, loss: 0.02708270
Epoch: [32] [  32/ 100] time: 399.0881, loss: 0.00607402
Epoch: [32] [  33/ 100] time: 399.2139, loss: 0.01260829
Epoch: [32] [  34/ 100] time: 399.3394, loss: 0.06369789
Epoch: [32] [  35/ 100] time: 399.4651, loss: 0.02769032
Epoch: [32] [  36/ 100] time: 399.5911, loss: 0.13528568
Epoch: [32] [  37/ 100] time: 399.7162, loss: 0.02295903
Epoch: [32] [  38/ 100] time: 399.8364, loss: 0.00892162
Epoch: [32] [  39/ 100] time: 3

Epoch: [33] [  66/ 100] time: 416.1451, loss: 0.00111029
Epoch: [33] [  67/ 100] time: 416.2664, loss: 0.01923026
Epoch: [33] [  68/ 100] time: 416.3876, loss: 0.00755501
Epoch: [33] [  69/ 100] time: 416.5090, loss: 0.00119569
Epoch: [33] [  70/ 100] time: 416.6301, loss: 0.00045190
Epoch: [33] [  71/ 100] time: 416.7515, loss: 0.00047995
Epoch: [33] [  72/ 100] time: 416.8726, loss: 0.00384027
Epoch: [33] [  73/ 100] time: 416.9906, loss: 0.00186876
Epoch: [33] [  74/ 100] time: 417.1071, loss: 0.00033589
Epoch: [33] [  75/ 100] time: 417.2236, loss: 0.01328179
Epoch: [33] [  76/ 100] time: 417.3401, loss: 0.00024672
Epoch: [33] [  77/ 100] time: 417.4576, loss: 0.00468922
Epoch: [33] [  78/ 100] time: 417.5742, loss: 0.01360340
Epoch: [33] [  79/ 100] time: 417.6907, loss: 0.00516624
Epoch: [33] [  80/ 100] time: 417.8072, loss: 0.00777768
Epoch: [33] [  81/ 100] time: 417.9253, loss: 0.00189086
Epoch: [33] [  82/ 100] time: 418.0416, loss: 0.00373040
Epoch: [33] [  83/ 100] time: 4

Epoch: [35] [   8/ 100] time: 434.8654, loss: 0.01664509
Epoch: [35] [   9/ 100] time: 434.9827, loss: 0.02306072
Epoch: [35] [  10/ 100] time: 435.0993, loss: 0.06070262
Epoch: [35] [  11/ 100] time: 435.2159, loss: 0.00565993
Epoch: [35] [  12/ 100] time: 435.3324, loss: 0.00302627
Epoch: [35] [  13/ 100] time: 435.4500, loss: 0.03944054
Epoch: [35] [  14/ 100] time: 435.5664, loss: 0.01609357
Epoch: [35] [  15/ 100] time: 435.6837, loss: 0.00453251
Epoch: [35] [  16/ 100] time: 435.8002, loss: 0.02301412
Epoch: [35] [  17/ 100] time: 435.9185, loss: 0.00810979
Epoch: [35] [  18/ 100] time: 436.0350, loss: 0.00254396
Epoch: [35] [  19/ 100] time: 436.1519, loss: 0.00352600
Epoch: [35] [  20/ 100] time: 436.2683, loss: 0.00256396
Epoch: [35] [  21/ 100] time: 436.3862, loss: 0.03637149
Epoch: [35] [  22/ 100] time: 436.5029, loss: 0.00070274
Epoch: [35] [  23/ 100] time: 436.6193, loss: 0.00217406
Epoch: [35] [  24/ 100] time: 436.7357, loss: 0.00893960
Epoch: [35] [  25/ 100] time: 4

Epoch: [36] [  52/ 100] time: 452.7493, loss: 0.00004338
Epoch: [36] [  53/ 100] time: 452.8657, loss: 0.00014995
Epoch: [36] [  54/ 100] time: 452.9843, loss: 0.00008677
Epoch: [36] [  55/ 100] time: 453.1006, loss: 0.00714514
Epoch: [36] [  56/ 100] time: 453.2167, loss: 0.00113253
Epoch: [36] [  57/ 100] time: 453.3335, loss: 0.00158209
Epoch: [36] [  58/ 100] time: 453.4512, loss: 0.00403757
Epoch: [36] [  59/ 100] time: 453.5678, loss: 0.00209452
Epoch: [36] [  60/ 100] time: 453.6842, loss: 0.00308242
Epoch: [36] [  61/ 100] time: 453.8006, loss: 0.00067782
Epoch: [36] [  62/ 100] time: 453.9169, loss: 0.00037509
Epoch: [36] [  63/ 100] time: 454.0331, loss: 0.00233684
Epoch: [36] [  64/ 100] time: 454.1495, loss: 0.01940534
Epoch: [36] [  65/ 100] time: 454.2659, loss: 0.00138791
Epoch: [36] [  66/ 100] time: 454.3826, loss: 0.01251601
Epoch: [36] [  67/ 100] time: 454.4993, loss: 0.00068438
Epoch: [36] [  68/ 100] time: 454.6158, loss: 0.00230016
Epoch: [36] [  69/ 100] time: 4

Epoch: [37] [  96/ 100] time: 470.5746, loss: 0.01222638
Epoch: [37] [  97/ 100] time: 470.6935, loss: 0.00795617
Epoch: [37] [  98/ 100] time: 470.8103, loss: 0.00118980
Epoch: [37] [  99/ 100] time: 470.9281, loss: 0.00005597
[37/50] - ptime: 12.3416 loss: 0.00791896 acc: 0.91667 lr: 0.00067717
Epoch: [38] [   0/ 100] time: 472.0845, loss: 0.00028956
Epoch: [38] [   1/ 100] time: 472.2000, loss: 0.00002472
Epoch: [38] [   2/ 100] time: 472.3165, loss: 0.00025959
Epoch: [38] [   3/ 100] time: 472.4346, loss: 0.00010561
Epoch: [38] [   4/ 100] time: 472.5515, loss: 0.00098394
Epoch: [38] [   5/ 100] time: 472.6678, loss: 0.00007562
Epoch: [38] [   6/ 100] time: 472.7838, loss: 0.00844230
Epoch: [38] [   7/ 100] time: 472.9004, loss: 0.00084507
Epoch: [38] [   8/ 100] time: 473.0182, loss: 0.00014261
Epoch: [38] [   9/ 100] time: 473.1345, loss: 0.00462671
Epoch: [38] [  10/ 100] time: 473.2508, loss: 0.01224879
Epoch: [38] [  11/ 100] time: 473.3678, loss: 0.00137841
Epoch: [38] [  12/

Epoch: [39] [  38/ 100] time: 489.3502, loss: 0.00027260
Epoch: [39] [  39/ 100] time: 489.4701, loss: 0.00003938
Epoch: [39] [  40/ 100] time: 489.5867, loss: 0.00001310
Epoch: [39] [  41/ 100] time: 489.7037, loss: 0.00923599
Epoch: [39] [  42/ 100] time: 489.8201, loss: 0.00017752
Epoch: [39] [  43/ 100] time: 489.9366, loss: 0.00080847
Epoch: [39] [  44/ 100] time: 490.0568, loss: 0.00007945
Epoch: [39] [  45/ 100] time: 490.1772, loss: 0.00093666
Epoch: [39] [  46/ 100] time: 490.2956, loss: 0.00155227
Epoch: [39] [  47/ 100] time: 490.4141, loss: 0.00836299
Epoch: [39] [  48/ 100] time: 490.5314, loss: 0.00091667
Epoch: [39] [  49/ 100] time: 490.6493, loss: 0.00011075
Epoch: [39] [  50/ 100] time: 490.7701, loss: 0.00039326
Epoch: [39] [  51/ 100] time: 490.8912, loss: 0.00918008
Epoch: [39] [  52/ 100] time: 491.0119, loss: 0.00032148
Epoch: [39] [  53/ 100] time: 491.1320, loss: 0.00534533
Epoch: [39] [  54/ 100] time: 491.2524, loss: 0.00013882
Epoch: [39] [  55/ 100] time: 4

Epoch: [40] [  82/ 100] time: 507.3823, loss: 0.00275117
Epoch: [40] [  83/ 100] time: 507.5005, loss: 0.00217295
Epoch: [40] [  84/ 100] time: 507.6179, loss: 0.16929486
Epoch: [40] [  85/ 100] time: 507.7355, loss: 0.14221977
Epoch: [40] [  86/ 100] time: 507.8539, loss: 0.02845010
Epoch: [40] [  87/ 100] time: 507.9724, loss: 0.02447795
Epoch: [40] [  88/ 100] time: 508.0918, loss: 0.15038979
Epoch: [40] [  89/ 100] time: 508.2103, loss: 0.01020718
Epoch: [40] [  90/ 100] time: 508.3284, loss: 0.01369105
Epoch: [40] [  91/ 100] time: 508.4483, loss: 0.06013414
Epoch: [40] [  92/ 100] time: 508.5665, loss: 0.03874881
Epoch: [40] [  93/ 100] time: 508.6852, loss: 0.01735328
Epoch: [40] [  94/ 100] time: 508.8031, loss: 0.00917216
Epoch: [40] [  95/ 100] time: 508.9213, loss: 0.00466764
Epoch: [40] [  96/ 100] time: 509.0402, loss: 0.00412704
Epoch: [40] [  97/ 100] time: 509.1571, loss: 0.02085896
Epoch: [40] [  98/ 100] time: 509.2761, loss: 0.08022909
Epoch: [40] [  99/ 100] time: 5

Epoch: [42] [  24/ 100] time: 535.6193, loss: 0.00250399
Epoch: [42] [  25/ 100] time: 535.7362, loss: 0.07750831
Epoch: [42] [  26/ 100] time: 535.8530, loss: 0.03094408
Epoch: [42] [  27/ 100] time: 535.9698, loss: 0.00106310
Epoch: [42] [  28/ 100] time: 536.0870, loss: 0.00352058
Epoch: [42] [  29/ 100] time: 536.2041, loss: 0.06137538
Epoch: [42] [  30/ 100] time: 536.3215, loss: 0.03321330
Epoch: [42] [  31/ 100] time: 536.4397, loss: 0.00703644
Epoch: [42] [  32/ 100] time: 536.5570, loss: 0.02696228
Epoch: [42] [  33/ 100] time: 536.6745, loss: 0.01720922
Epoch: [42] [  34/ 100] time: 536.7915, loss: 0.05143535
Epoch: [42] [  35/ 100] time: 536.9095, loss: 0.00954443
Epoch: [42] [  36/ 100] time: 537.0262, loss: 0.00772809
Epoch: [42] [  37/ 100] time: 537.1443, loss: 0.01395418
Epoch: [42] [  38/ 100] time: 537.2617, loss: 0.01667936
Epoch: [42] [  39/ 100] time: 537.3802, loss: 0.00512558
Epoch: [42] [  40/ 100] time: 537.4976, loss: 0.00052271
Epoch: [42] [  41/ 100] time: 5

Epoch: [43] [  68/ 100] time: 553.5383, loss: 0.00732172
Epoch: [43] [  69/ 100] time: 553.6548, loss: 0.01093626
Epoch: [43] [  70/ 100] time: 553.7723, loss: 0.00095717
Epoch: [43] [  71/ 100] time: 553.8888, loss: 0.00089397
Epoch: [43] [  72/ 100] time: 554.0058, loss: 0.01644346
Epoch: [43] [  73/ 100] time: 554.1241, loss: 0.01215653
Epoch: [43] [  74/ 100] time: 554.2407, loss: 0.00208856
Epoch: [43] [  75/ 100] time: 554.3579, loss: 0.00108738
Epoch: [43] [  76/ 100] time: 554.4761, loss: 0.00346587
Epoch: [43] [  77/ 100] time: 554.5938, loss: 0.00082053
Epoch: [43] [  78/ 100] time: 554.7102, loss: 0.03718815
Epoch: [43] [  79/ 100] time: 554.8265, loss: 0.01582868
Epoch: [43] [  80/ 100] time: 554.9452, loss: 0.00748543
Epoch: [43] [  81/ 100] time: 555.0630, loss: 0.00635210
Epoch: [43] [  82/ 100] time: 555.1817, loss: 0.00194173
Epoch: [43] [  83/ 100] time: 555.2990, loss: 0.00183112
Epoch: [43] [  84/ 100] time: 555.4174, loss: 0.04958294
Epoch: [43] [  85/ 100] time: 5

Epoch: [45] [  10/ 100] time: 572.3274, loss: 0.01940287
Epoch: [45] [  11/ 100] time: 572.4451, loss: 0.00353343
Epoch: [45] [  12/ 100] time: 572.5616, loss: 0.00142746
Epoch: [45] [  13/ 100] time: 572.6792, loss: 0.01044926
Epoch: [45] [  14/ 100] time: 572.7959, loss: 0.00219584
Epoch: [45] [  15/ 100] time: 572.9132, loss: 0.06203147
Epoch: [45] [  16/ 100] time: 573.0298, loss: 0.00307803
Epoch: [45] [  17/ 100] time: 573.1482, loss: 0.00411007
Epoch: [45] [  18/ 100] time: 573.2648, loss: 0.00089341
Epoch: [45] [  19/ 100] time: 573.3829, loss: 0.00598542
Epoch: [45] [  20/ 100] time: 573.4996, loss: 0.00173625
Epoch: [45] [  21/ 100] time: 573.6164, loss: 0.02618721
Epoch: [45] [  22/ 100] time: 573.7328, loss: 0.00236021
Epoch: [45] [  23/ 100] time: 573.8505, loss: 0.00559454
Epoch: [45] [  24/ 100] time: 573.9673, loss: 0.02332485
Epoch: [45] [  25/ 100] time: 574.0836, loss: 0.02139883
Epoch: [45] [  26/ 100] time: 574.2018, loss: 0.00028186
Epoch: [45] [  27/ 100] time: 5

Epoch: [46] [  54/ 100] time: 590.2242, loss: 0.01500958
Epoch: [46] [  55/ 100] time: 590.3417, loss: 0.00355528
Epoch: [46] [  56/ 100] time: 590.4598, loss: 0.00014741
Epoch: [46] [  57/ 100] time: 590.5774, loss: 0.01505694
Epoch: [46] [  58/ 100] time: 590.6949, loss: 0.00262816
Epoch: [46] [  59/ 100] time: 590.8112, loss: 0.00082432
Epoch: [46] [  60/ 100] time: 590.9279, loss: 0.00152075
Epoch: [46] [  61/ 100] time: 591.0449, loss: 0.00030306
Epoch: [46] [  62/ 100] time: 591.1624, loss: 0.00099294
Epoch: [46] [  63/ 100] time: 591.2796, loss: 0.00037574
Epoch: [46] [  64/ 100] time: 591.3969, loss: 0.00066254
Epoch: [46] [  65/ 100] time: 591.5140, loss: 0.00489669
Epoch: [46] [  66/ 100] time: 591.6311, loss: 0.00096354
Epoch: [46] [  67/ 100] time: 591.7483, loss: 0.00146292
Epoch: [46] [  68/ 100] time: 591.8653, loss: 0.00010141
Epoch: [46] [  69/ 100] time: 591.9831, loss: 0.00328869
Epoch: [46] [  70/ 100] time: 592.1002, loss: 0.00085480
Epoch: [46] [  71/ 100] time: 5

Epoch: [47] [  98/ 100] time: 608.1815, loss: 0.00006129
Epoch: [47] [  99/ 100] time: 608.2984, loss: 0.00152028
[47/50] - ptime: 12.4048 loss: 0.00355279 acc: 0.94583 lr: 0.00060945
Epoch: [48] [   0/ 100] time: 609.4462, loss: 0.00299767
Epoch: [48] [   1/ 100] time: 609.5611, loss: 0.00031071
Epoch: [48] [   2/ 100] time: 609.6776, loss: 0.00014838
Epoch: [48] [   3/ 100] time: 609.7945, loss: 0.00235947
Epoch: [48] [   4/ 100] time: 609.9113, loss: 0.00721442
Epoch: [48] [   5/ 100] time: 610.0281, loss: 0.00036556
Epoch: [48] [   6/ 100] time: 610.1460, loss: 0.00004935
Epoch: [48] [   7/ 100] time: 610.2641, loss: 0.00026222
Epoch: [48] [   8/ 100] time: 610.3813, loss: 0.00145317
Epoch: [48] [   9/ 100] time: 610.4983, loss: 0.00093165
Epoch: [48] [  10/ 100] time: 610.6149, loss: 0.00065836
Epoch: [48] [  11/ 100] time: 610.7316, loss: 0.00003584
Epoch: [48] [  12/ 100] time: 610.8481, loss: 0.00007847
Epoch: [48] [  13/ 100] time: 610.9648, loss: 0.00016572
Epoch: [48] [  14/

Epoch: [49] [  40/ 100] time: 626.8827, loss: 0.00060403
Epoch: [49] [  41/ 100] time: 626.9990, loss: 0.00023408
Epoch: [49] [  42/ 100] time: 627.1159, loss: 0.00010576
Epoch: [49] [  43/ 100] time: 627.2342, loss: 0.00022511
Epoch: [49] [  44/ 100] time: 627.3523, loss: 0.00451050
Epoch: [49] [  45/ 100] time: 627.4708, loss: 0.00133127
Epoch: [49] [  46/ 100] time: 627.5877, loss: 0.00006882
Epoch: [49] [  47/ 100] time: 627.7054, loss: 0.00013272
Epoch: [49] [  48/ 100] time: 627.8225, loss: 0.00009516
Epoch: [49] [  49/ 100] time: 627.9389, loss: 0.00025911
Epoch: [49] [  50/ 100] time: 628.0565, loss: 0.00063373
Epoch: [49] [  51/ 100] time: 628.1744, loss: 0.00127328
Epoch: [49] [  52/ 100] time: 628.2935, loss: 0.00014143
Epoch: [49] [  53/ 100] time: 628.4119, loss: 0.00005771
Epoch: [49] [  54/ 100] time: 628.5291, loss: 0.00043919
Epoch: [49] [  55/ 100] time: 628.6459, loss: 0.00010150
Epoch: [49] [  56/ 100] time: 628.7626, loss: 0.00006315
Epoch: [49] [  57/ 100] time: 6

Epoch: [50] [  84/ 100] time: 644.8243, loss: 0.00067153
Epoch: [50] [  85/ 100] time: 644.9409, loss: 0.00007160
Epoch: [50] [  86/ 100] time: 645.0574, loss: 0.00080791
Epoch: [50] [  87/ 100] time: 645.1741, loss: 0.00794054
Epoch: [50] [  88/ 100] time: 645.2937, loss: 0.00037992
Epoch: [50] [  89/ 100] time: 645.4128, loss: 0.00020158
Epoch: [50] [  90/ 100] time: 645.5295, loss: 0.01265701
Epoch: [50] [  91/ 100] time: 645.6466, loss: 0.00430959
Epoch: [50] [  92/ 100] time: 645.7631, loss: 0.00008458
Epoch: [50] [  93/ 100] time: 645.8826, loss: 0.00020037
Epoch: [50] [  94/ 100] time: 645.9976, loss: 0.00014918
Epoch: [50] [  95/ 100] time: 646.1124, loss: 0.00002476
Epoch: [50] [  96/ 100] time: 646.2306, loss: 0.00003000
Epoch: [50] [  97/ 100] time: 646.3571, loss: 0.00964777
Epoch: [50] [  98/ 100] time: 646.4796, loss: 0.00244160
Epoch: [50] [  99/ 100] time: 646.5978, loss: 0.00002069
[50/50] - ptime: 12.4046 loss: 0.00198569 acc: 0.93750 lr: 0.00059049
Avg per epoch ptim

In [ ]:
import pygame

file='/home/huiqy/Music/CloudMusic/All_Time_Low.mp3' #文件名是完整路径名
pygame.mixer.init() #初始化音频
track = pygame.mixer.music.load(file)#载入音乐文件
pygame.mixer.music.play()#开始播放
time.sleep(60)#播放10秒
pygame.mixer.music.stop()#停止播放